apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secrets
  labels: {{- include "auth.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: auth-secrets
  data:
    - secretKey: pg-password
      remoteRef:
        key: {{ .Values.secretStore.keys.pgPassword }}
    - secretKey: jwt-signing-key
      remoteRef:
        key: {{ .Values.secretStore.keys.jwtSigningKey }}
    {{- if .Values.providers.google.enabled }}
    - secretKey: google-client-id
      remoteRef:
        key: {{ .Values.secretStore.keys.googleClientId }}
    - secretKey: google-client-secret
      remoteRef:
        key: {{ .Values.secretStore.keys.googleClientSecret }}
    {{- end }}
    {{- if .Values.providers.twitch.enabled }}
    - secretKey: twitch-client-id
      remoteRef:
        key: {{ .Values.secretStore.keys.twitchClientId }}
    - secretKey: twitch-client-secret
      remoteRef:
        key: {{ .Values.secretStore.keys.twitchClientSecret }}
    {{- end }}
