apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: enrichment-secrets
  labels: {{- include "enrichment.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: enrichment-secrets
  data:
    - secretKey: mongo-password
      remoteRef:
        key: {{ .Values.secretStore.keys.mongoPassword }}
    - secretKey: internal-service-token
      remoteRef:
        key: {{ .Values.secretStore.keys.internalServiceToken }}
    {{- if eq .Values.igdb.mode "real" }}
    - secretKey: igdb-client-id
      remoteRef:
        key: {{ .Values.secretStore.keys.igdbClientId }}
    - secretKey: igdb-client-secret
      remoteRef:
        key: {{ .Values.secretStore.keys.igdbClientSecret }}
    {{- end }}
    {{- if eq .Values.pricecharting.mode "real" }}
    - secretKey: pricecharting-api-key
      remoteRef:
        key: {{ .Values.secretStore.keys.pricechartingApiKey }}
    {{- end }}
