{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: enrichment-mongo
  labels:
    app.kubernetes.io/name: enrichment-mongo
    app.kubernetes.io/part-of: vgkeep
spec:
  selector:
    app.kubernetes.io/name: enrichment-mongo
  ports:
    - { name: mongo, port: 27017, targetPort: mongo }
    - name: metrics
      port: 9216
      targetPort: metrics
{{- end }}
