{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mongo
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-mongo
    app.kubernetes.io/part-of: vgkeep
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-mongo
  ports:
    - { name: mongo, port: 27017, targetPort: mongo }
    - name: metrics
      port: 9216
      targetPort: metrics
{{- end }}
