apiVersion: v1
kind: Service
metadata:
  name: enrichment
  labels: {{- include "enrichment.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: enrichment
  ports:
    - { name: http, port: 8080, targetPort: http }
