{{- if .Values.valkey.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: enrichment-valkey-tls
  labels: {{- include "enrichment.labels" . | nindent 4 }}
spec:
  secretName: enrichment-valkey-tls
  duration: 2160h
  dnsNames:
    - {{ include "enrichment.valkeyHost" . }}
    - {{ include "enrichment.valkeyHost" . }}.{{ .Release.Namespace }}.svc
    - {{ include "enrichment.valkeyHost" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: vg-ca
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
