apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: collection
  labels: {{- include "collection.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: collection
