{{- if .Values.postgres.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: collection-pg-tls
  labels: {{- include "collection.labels" . | nindent 4 }}
spec:
  secretName: collection-pg-tls
  duration: 2160h
  dnsNames:
    - {{ include "collection.pgHost" . }}
    - {{ include "collection.pgHost" . }}.{{ .Release.Namespace }}.svc
    - {{ include "collection.pgHost" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: vg-ca
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
