{{- if .Values.valkey.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: collection-valkey
  labels:
    app.kubernetes.io/name: collection-valkey
    app.kubernetes.io/part-of: vg-collect
spec:
  selector:
    app.kubernetes.io/name: collection-valkey
  ports:
    - { name: valkey, port: 6379, targetPort: valkey }
    - name: metrics
      port: 9121
      targetPort: metrics
{{- end }}
