apiVersion: v1
kind: Service
metadata:
  name: bff
  labels: {{- include "bff.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: bff
  ports:
    - { name: http, port: 8080, targetPort: http }
