// Package userapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package userapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/levonn-dev/vgkeep/libs/go/contract/common"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ProfileCard The cross-user projection of a user. Never email, never roles.
type ProfileCard = externalRef0.ProfileCard

// UpdateUserRequest Absent fields keep their value; an empty avatar_url clears it.
type UpdateUserRequest struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// Handle New typed form. Any change to the typed string, including a decoration-only edit (case or underscores only, same folded key), still consumes the cooldown: one change per cooldown window (429 handle_cooldown); folded-key collisions answer 409 handle_taken.
	Handle            *externalRef0.Handle       `json:"handle,omitempty"`
	LandingPage       *externalRef0.LandingPage  `json:"landing_page,omitempty"`
	PreferredCurrency *externalRef0.CurrencyCode `json:"preferred_currency,omitempty"`
	ProfileVisibility *externalRef0.Visibility   `json:"profile_visibility,omitempty"`
}

// UpsertUserRequest defines model for UpsertUserRequest.
type UpsertUserRequest struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// DisplayName The provider's display name. Used ONLY as the handle derivation seed when this upsert creates the account; it is not stored and never overwrites an existing handle.
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`

	// LocaleHint BCP 47 language tag from the login request's Accept-Language header. Applied only when this upsert creates the account: it seeds preferred_currency and never touches an existing user.
	LocaleHint *string `json:"locale_hint,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl *string   `json:"avatar_url,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`

	// Handle The user's single identity. 2-30 chars, alphanumeric plus interior underscores; case and underscores are decoration (uniqueness folds them).
	Handle externalRef0.Handle `json:"handle"`
	Id     openapi_types.UUID  `json:"id"`

	// LandingPage Where the app opens after sign-in. Private preference, defaulted to feed for every account; never on ProfileCard.
	LandingPage externalRef0.LandingPage `json:"landing_page"`

	// PreferredCurrency The display currency the SPA converts market values into. Defaulted from locale_hint at account creation, USD when no hint maps.
	PreferredCurrency externalRef0.CurrencyCode `json:"preferred_currency"`
	ProfileVisibility externalRef0.Visibility   `json:"profile_visibility"`
	Roles             []externalRef0.Role       `json:"roles"`
	UpdatedAt         time.Time                 `json:"updated_at"`
}

// BadRequest defines model for BadRequest.
type BadRequest = externalRef0.Problem

// Conflict defines model for Conflict.
type Conflict = externalRef0.Problem

// Forbidden defines model for Forbidden.
type Forbidden = externalRef0.Problem

// InternalError defines model for InternalError.
type InternalError = externalRef0.Problem

// NotFound defines model for NotFound.
type NotFound = externalRef0.Problem

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = externalRef0.Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = externalRef0.Problem

// GetSharedProfilesByIdsParams defines parameters for GetSharedProfilesByIds.
type GetSharedProfilesByIdsParams struct {
	Ids []openapi_types.UUID `form:"ids" json:"ids"`
}

// SearchSharedProfilesParams defines parameters for SearchSharedProfiles.
type SearchSharedProfilesParams struct {
	Q externalRef0.UserSearchQ `form:"q" json:"q"`
}

// UpsertUserJSONRequestBody defines body for UpsertUser for application/json ContentType.
type UpsertUserJSONRequestBody = UpsertUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// UpsertUserWithBody Create-or-update a user at login time (auth service credential only)
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
	UpsertUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertUser Create-or-update a user at login time (auth service credential only)
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
	UpsertUser(ctx context.Context, body UpsertUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSharedProfilesByIds Batch profile cards for hydration (returned regardless of visibility - actions are signed; page access stays gated)
	//
	// Corresponds with GET /shared/profiles/by-ids (the `GetSharedProfilesByIds` operationId).
	GetSharedProfilesByIds(ctx context.Context, params *GetSharedProfilesByIdsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchSharedProfiles Substring search over listed profiles' folded handles
	//
	// Corresponds with GET /shared/profiles/search (the `SearchSharedProfiles` operationId).
	SearchSharedProfiles(ctx context.Context, params *SearchSharedProfilesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSharedProfile Resolve a handle to its profile card (any authenticated caller; non-private only)
	//
	// Corresponds with GET /shared/profiles/{handle} (the `GetSharedProfile` operationId).
	GetSharedProfile(ctx context.Context, handle string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUser Delete a user account (self only); idempotent
	//
	// Corresponds with DELETE /users/{userId} (the `DeleteUser` operationId).
	DeleteUser(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUser Fetch a user (self, a service credential, or admin)
	//
	// Corresponds with GET /users/{userId} (the `GetUser` operationId).
	GetUser(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateUserWithBody Self-service profile update
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
	UpdateUserWithBody(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateUser Self-service profile update
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
	UpdateUser(ctx context.Context, userId openapi_types.UUID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// UpsertUserWithBody Create-or-update a user at login time (auth service credential only)
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
func (c *Client) UpsertUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertUser Create-or-update a user at login time (auth service credential only)
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
func (c *Client) UpsertUser(ctx context.Context, body UpsertUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSharedProfilesByIds Batch profile cards for hydration (returned regardless of visibility - actions are signed; page access stays gated)
//
// Corresponds with GET /shared/profiles/by-ids (the `GetSharedProfilesByIds` operationId).
func (c *Client) GetSharedProfilesByIds(ctx context.Context, params *GetSharedProfilesByIdsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSharedProfilesByIdsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SearchSharedProfiles Substring search over listed profiles' folded handles
//
// Corresponds with GET /shared/profiles/search (the `SearchSharedProfiles` operationId).
func (c *Client) SearchSharedProfiles(ctx context.Context, params *SearchSharedProfilesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchSharedProfilesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSharedProfile Resolve a handle to its profile card (any authenticated caller; non-private only)
//
// Corresponds with GET /shared/profiles/{handle} (the `GetSharedProfile` operationId).
func (c *Client) GetSharedProfile(ctx context.Context, handle string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSharedProfileRequest(c.Server, handle)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteUser Delete a user account (self only); idempotent
//
// Corresponds with DELETE /users/{userId} (the `DeleteUser` operationId).
func (c *Client) DeleteUser(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetUser Fetch a user (self, a service credential, or admin)
//
// Corresponds with GET /users/{userId} (the `GetUser` operationId).
func (c *Client) GetUser(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateUserWithBody Self-service profile update
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
func (c *Client) UpdateUserWithBody(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUserRequestWithBody(c.Server, userId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateUser Self-service profile update
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
func (c *Client) UpdateUser(ctx context.Context, userId openapi_types.UUID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUserRequest(c.Server, userId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewUpsertUserRequest calls the generic UpsertUser builder with application/json body
func NewUpsertUserRequest(server string, body UpsertUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpsertUserRequestWithBody(server, "application/json", bodyReader)
}

// NewUpsertUserRequestWithBody constructs an http.Request for the UpsertUser method, with any body, and a specified content type
func NewUpsertUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/users/upsert")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetSharedProfilesByIdsRequest constructs an http.Request for the GetSharedProfilesByIds method
func NewGetSharedProfilesByIdsRequest(server string, params *GetSharedProfilesByIdsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/shared/profiles/by-ids")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Ids != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "ids", params.Ids, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSearchSharedProfilesRequest constructs an http.Request for the SearchSharedProfiles method
func NewSearchSharedProfilesRequest(server string, params *SearchSharedProfilesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/shared/profiles/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSharedProfileRequest constructs an http.Request for the GetSharedProfile method
func NewGetSharedProfileRequest(server string, handle string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "handle", handle, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/shared/profiles/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteUserRequest constructs an http.Request for the DeleteUser method
func NewDeleteUserRequest(server string, userId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "userId", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserRequest constructs an http.Request for the GetUser method
func NewGetUserRequest(server string, userId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "userId", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateUserRequest calls the generic UpdateUser builder with application/json body
func NewUpdateUserRequest(server string, userId openapi_types.UUID, body UpdateUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateUserRequestWithBody(server, userId, "application/json", bodyReader)
}

// NewUpdateUserRequestWithBody constructs an http.Request for the UpdateUser method, with any body, and a specified content type
func NewUpdateUserRequestWithBody(server string, userId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "userId", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// UpsertUserWithBodyWithResponse Create-or-update a user at login time (auth service credential only)
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
	UpsertUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertUserResponse, error)

	// UpsertUserWithResponse Create-or-update a user at login time (auth service credential only)
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
	UpsertUserWithResponse(ctx context.Context, body UpsertUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertUserResponse, error)

	// GetSharedProfilesByIdsWithResponse Batch profile cards for hydration (returned regardless of visibility - actions are signed; page access stays gated)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /shared/profiles/by-ids (the `GetSharedProfilesByIds` operationId).
	GetSharedProfilesByIdsWithResponse(ctx context.Context, params *GetSharedProfilesByIdsParams, reqEditors ...RequestEditorFn) (*GetSharedProfilesByIdsResponse, error)

	// SearchSharedProfilesWithResponse Substring search over listed profiles' folded handles
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /shared/profiles/search (the `SearchSharedProfiles` operationId).
	SearchSharedProfilesWithResponse(ctx context.Context, params *SearchSharedProfilesParams, reqEditors ...RequestEditorFn) (*SearchSharedProfilesResponse, error)

	// GetSharedProfileWithResponse Resolve a handle to its profile card (any authenticated caller; non-private only)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /shared/profiles/{handle} (the `GetSharedProfile` operationId).
	GetSharedProfileWithResponse(ctx context.Context, handle string, reqEditors ...RequestEditorFn) (*GetSharedProfileResponse, error)

	// DeleteUserWithResponse Delete a user account (self only); idempotent
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /users/{userId} (the `DeleteUser` operationId).
	DeleteUserWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteUserResponse, error)

	// GetUserWithResponse Fetch a user (self, a service credential, or admin)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /users/{userId} (the `GetUser` operationId).
	GetUserWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetUserResponse, error)

	// UpdateUserWithBodyWithResponse Self-service profile update
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
	UpdateUserWithBodyWithResponse(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error)

	// UpdateUserWithResponse Self-service profile update
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
	UpdateUserWithResponse(ctx context.Context, userId openapi_types.UUID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error)
}

type UpsertUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *User
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Forbidden
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpsertUserResponse) GetJSON200() *User {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r UpsertUserResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r UpsertUserResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r UpsertUserResponse) GetApplicationproblemJSON403() *Forbidden {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r UpsertUserResponse) GetApplicationproblemJSONDefault() *InternalError {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r UpsertUserResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpsertUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpsertUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpsertUserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSharedProfilesByIdsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Profiles []ProfileCard `json:"profiles"`
	}
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetSharedProfilesByIdsResponse) GetJSON200() *struct {
	Profiles []ProfileCard `json:"profiles"`
} {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r GetSharedProfilesByIdsResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetSharedProfilesByIdsResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetSharedProfilesByIdsResponse) GetApplicationproblemJSONDefault() *InternalError {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetSharedProfilesByIdsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetSharedProfilesByIdsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSharedProfilesByIdsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSharedProfilesByIdsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SearchSharedProfilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Profiles []ProfileCard `json:"profiles"`
	}
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SearchSharedProfilesResponse) GetJSON200() *struct {
	Profiles []ProfileCard `json:"profiles"`
} {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r SearchSharedProfilesResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r SearchSharedProfilesResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r SearchSharedProfilesResponse) GetApplicationproblemJSONDefault() *InternalError {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r SearchSharedProfilesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SearchSharedProfilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchSharedProfilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SearchSharedProfilesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSharedProfileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ProfileCard
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *NotFound
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetSharedProfileResponse) GetJSON200() *ProfileCard {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetSharedProfileResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetSharedProfileResponse) GetApplicationproblemJSON404() *NotFound {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetSharedProfileResponse) GetApplicationproblemJSONDefault() *InternalError {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetSharedProfileResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetSharedProfileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSharedProfileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSharedProfileResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Forbidden
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *InternalError
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r DeleteUserResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r DeleteUserResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r DeleteUserResponse) GetApplicationproblemJSON403() *Forbidden {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r DeleteUserResponse) GetApplicationproblemJSONDefault() *InternalError {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r DeleteUserResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteUserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *User
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Forbidden
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *NotFound
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetUserResponse) GetJSON200() *User {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r GetUserResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetUserResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r GetUserResponse) GetApplicationproblemJSON403() *Forbidden {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetUserResponse) GetApplicationproblemJSON404() *NotFound {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetUserResponse) GetApplicationproblemJSONDefault() *InternalError {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetUserResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetUserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *User
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Forbidden
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *NotFound
	// ApplicationproblemJSON409 the response for an HTTP 409 `application/problem+json` response
	ApplicationproblemJSON409 *Conflict
	// ApplicationproblemJSON429 the response for an HTTP 429 `application/problem+json` response
	ApplicationproblemJSON429 *TooManyRequests
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdateUserResponse) GetJSON200() *User {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON403() *Forbidden {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON404() *NotFound {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON409 returns the response for an HTTP 409 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON409() *Conflict {
	return r.ApplicationproblemJSON409
}

// GetApplicationproblemJSON429 returns the response for an HTTP 429 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON429() *TooManyRequests {
	return r.ApplicationproblemJSON429
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSONDefault() *InternalError {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r UpdateUserResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateUserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// UpsertUserWithBodyWithResponse Create-or-update a user at login time (auth service credential only)
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
func (c *ClientWithResponses) UpsertUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertUserResponse, error) {
	rsp, err := c.UpsertUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertUserResponse(rsp)
}

// UpsertUserWithResponse Create-or-update a user at login time (auth service credential only)
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
func (c *ClientWithResponses) UpsertUserWithResponse(ctx context.Context, body UpsertUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertUserResponse, error) {
	rsp, err := c.UpsertUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertUserResponse(rsp)
}

// GetSharedProfilesByIdsWithResponse Batch profile cards for hydration (returned regardless of visibility - actions are signed; page access stays gated)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /shared/profiles/by-ids (the `GetSharedProfilesByIds` operationId).
func (c *ClientWithResponses) GetSharedProfilesByIdsWithResponse(ctx context.Context, params *GetSharedProfilesByIdsParams, reqEditors ...RequestEditorFn) (*GetSharedProfilesByIdsResponse, error) {
	rsp, err := c.GetSharedProfilesByIds(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSharedProfilesByIdsResponse(rsp)
}

// SearchSharedProfilesWithResponse Substring search over listed profiles' folded handles
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /shared/profiles/search (the `SearchSharedProfiles` operationId).
func (c *ClientWithResponses) SearchSharedProfilesWithResponse(ctx context.Context, params *SearchSharedProfilesParams, reqEditors ...RequestEditorFn) (*SearchSharedProfilesResponse, error) {
	rsp, err := c.SearchSharedProfiles(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchSharedProfilesResponse(rsp)
}

// GetSharedProfileWithResponse Resolve a handle to its profile card (any authenticated caller; non-private only)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /shared/profiles/{handle} (the `GetSharedProfile` operationId).
func (c *ClientWithResponses) GetSharedProfileWithResponse(ctx context.Context, handle string, reqEditors ...RequestEditorFn) (*GetSharedProfileResponse, error) {
	rsp, err := c.GetSharedProfile(ctx, handle, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSharedProfileResponse(rsp)
}

// DeleteUserWithResponse Delete a user account (self only); idempotent
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /users/{userId} (the `DeleteUser` operationId).
func (c *ClientWithResponses) DeleteUserWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteUserResponse, error) {
	rsp, err := c.DeleteUser(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserResponse(rsp)
}

// GetUserWithResponse Fetch a user (self, a service credential, or admin)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /users/{userId} (the `GetUser` operationId).
func (c *ClientWithResponses) GetUserWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetUserResponse, error) {
	rsp, err := c.GetUser(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserResponse(rsp)
}

// UpdateUserWithBodyWithResponse Self-service profile update
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
func (c *ClientWithResponses) UpdateUserWithBodyWithResponse(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	rsp, err := c.UpdateUserWithBody(ctx, userId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUserResponse(rsp)
}

// UpdateUserWithResponse Self-service profile update
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
func (c *ClientWithResponses) UpdateUserWithResponse(ctx context.Context, userId openapi_types.UUID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	rsp, err := c.UpdateUser(ctx, userId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUserResponse(rsp)
}

// ParseUpsertUserResponse parses an HTTP response from a UpsertUserWithResponse call
func ParseUpsertUserResponse(rsp *http.Response) (*UpsertUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpsertUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetSharedProfilesByIdsResponse parses an HTTP response from a GetSharedProfilesByIdsWithResponse call
func ParseGetSharedProfilesByIdsResponse(rsp *http.Response) (*GetSharedProfilesByIdsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSharedProfilesByIdsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Profiles []ProfileCard `json:"profiles"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseSearchSharedProfilesResponse parses an HTTP response from a SearchSharedProfilesWithResponse call
func ParseSearchSharedProfilesResponse(rsp *http.Response) (*SearchSharedProfilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchSharedProfilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Profiles []ProfileCard `json:"profiles"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetSharedProfileResponse parses an HTTP response from a GetSharedProfileWithResponse call
func ParseGetSharedProfileResponse(rsp *http.Response) (*GetSharedProfileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSharedProfileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProfileCard
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteUserResponse parses an HTTP response from a DeleteUserWithResponse call
func ParseDeleteUserResponse(rsp *http.Response) (*DeleteUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetUserResponse parses an HTTP response from a GetUserWithResponse call
func ParseGetUserResponse(rsp *http.Response) (*GetUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateUserResponse parses an HTTP response from a UpdateUserWithResponse call
func ParseUpdateUserResponse(rsp *http.Response) (*UpdateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptc9y2Ef4rO2xmLE950lnWtPHpQ0Z26tYdx1HjOJnGVTk4YHlEBAI0AJ500dx/7yxA8sg76m2iREmm",
	"nyQABLBYPPvsC+4q4aasjEbtXTK7SipmWYkebWhxU5ZGZ7VD+x6Z5cW/qFfqZJZ8qtGukjTRrERqJmli",
	"8VMtLYpk5m2NaeJ4gSWjGSW7fIt64Ytk9pejNCmlbpvP0sSvKlrBeSv1Ilmv17SSq4x2GIR4ycQ3+KlG",
	"56NI2qMO/7KqUpIzL40+qKyZKyz//KMzmsY2e39mMU9myZ8ONgc9iKPuoDnfaZwc9xbouJUVrZrMku+Y",
	"kiJsATmTqrYIe9wIBKmXNJTNjVgdg0DPpAJShgNfIOQSlXiarNPkldG5kvwxhD/RxhdogXFuau3BXGiS",
	"jnkomBYKnzjIjRIo4BxXzbniSObZOeog/2tj51II1I9wgDfa1XkuuUTtwRqFJNAb7dFqpv5mrbGPINQH",
	"jZcVco8CHNol2omTAlt4kITvjH9tai0eQbh3xkMe9l6nybfGfMX0qrEe9wji/COgCXjB9AIFeGPAIkft",
	"1RbeuDFKmIsIuQ+a1b4wVv6Ej6HDr6RzUi8OGhMHb85RJ/RdswZtcWpNLhW+YjaIOFzh2wKBW+PchKgT",
	"Kmt+RB5IxOTAgDr34R0u0QKWTKoUdGgQxN1+kiaVNRVaLyMDsiXzzGa1VdTa4ss0iSq847njjdC0Kp4g",
	"W0on51JJv7rjEt9tJqzThA6TyaCE3NiS+WSW1LUUyS6z913Ex25id4BRkc66ZcyclBjwUQnm8YND23MM",
	"W9Q3d8QZgYYdnCNWRMvSwpKpGo+BacCy8ivY6Ba4QmYdSH/bDfTc2eH06PP0pithSn2dJ7OP97qcsx2z",
	"xgugTQSQjvfhRK8aowJvgsOJo1GCFKTmqhZSL4CBQG5ssJiJ0WoFKKSHPc4cgrFQa4HWcWPRAQ2n4FiJ",
	"Pb/wNAXnpVLAjXZ1699ae52B0a19Q4W2G4ALqYW5gL2jwxc7Rn7crD8hv8ONUtJJox0w7S7QwtH0xcAP",
	"7f9Hk1IV03SkrGKLu6L9bZxySjMC5DFHa1FkvLYWNb8r5F81n78y4uFsZz0KbYfWb0H752FRSFcptspi",
	"pDZGVZU1SynQPnHQfBwimX344FDA1+/e/htYvPZ4KyDQymWMihyigIsCNfhCOqiD/MAtMt9ApYk+jkF6",
	"kA608eC8sSiAadEQn1mivbCSppBlXkrnCbxxO7r+kXMF5hwlRGU4U5gVUo8ww8tXp3D0V1BML2pG9sMW",
	"kFtTBlmVWUgNNqr+iYMTzrHyk7ftxwUyQdx9Qm4IRbCYO51+RqcnXTnYBWFPEd7UvNjSQnAXQQdbcfTN",
	"/Br1s3X/o3Tq0N4Gsx0dxzOKjPkB8xMxT7ws8X439tB8SagmtT1xQK5cIUiB2ku/2ofDyfMpMZZ1KTBV",
	"FUzXJVrJoVK1A0nRpRwS4zEEtqRb6tMls9gjV9irtfxUo0YXw+pw/+XThrzu5CF3Oe5e6hiw3Y5Ovi/Q",
	"YsRkVYGpkAg392jByYWeSL0Pp8GssYEoao4pCMxZrXyI3iDH6IKAwLramHZjxRp6YVFz8HHOvde5huw7",
	"etktb3UmRed8f3pCXmuJ1jsomT1HH/1/uGazD192ZwsM0OMNYL5LmwLUpdEpfHj/ZbR2bSB8VbLKded8",
	"kHAqhIAhy/ZYujsu8U2TGjVwYtayGJuFQOk+RrrFIQGkLZHcFKa1go/e9xasB+QxEHKMncYwEAoVntLA",
	"ZJb89+PJ5Iezq+frz8YMasgUQ4f5fDqoRRymg1XZ5KeTyQ/TyYuzvS9mm1Z2djVNDz9f98affnHT1n2r",
	"nF0lqOuSVEthT0wKkjQhuyJNX1bK2D5L76zW5i07fM0bxdw992mDmVi8GOVlqZ1nmuPooPPM1643RNy5",
	"QBuQKL0anxU7rm4BXhhtl+m2ugEf/TONBjl5rRQUpnYUvAqEpeFsXisWaIxytYbTKKeXHGGvWZFiFlcw",
	"iyINHoCIZZ7nYFGxVXD53iIrw6IOlmjnzMtI++nmslmV4SVHFOGeSWbUPtPGZzFbp75YJyIzMVagbS0v",
	"q4nBZC4jRLSVvAiza82WTCo2DypC7e0qrMhr50056Go3ybtiTmvOXVC+6Qkxd0IuK7rMjCmLTKwyJfV5",
	"EKIb6a/ddXbzm0JN+HdTLes1OVNqzvh5r6udlMWsezMQKpP9tjWi5j6LuUdvwGJu0RW9HkJP/4t2acWc",
	"z1qxqS31eTai89CfM6lCq4zlgW6Vvg7of6kzOpMyi6YjKC9JE2PlQuqsfwftIUrmeRFWb3vCRZqyrHWU",
	"rd/f7tbva2P4XnfnxEWPs7fmhzkZhlIaWWBQHR2hsmZh0bler8XahbUsBnm3PnOo8iw3SpkLahXU7O/m",
	"6nlQndHXdVcYmHLYaZnHTMlSetz63KIzahl6PVtkWzZGXSGEdk2jv6k3JiuZXrVbZptl6fM6FKAIF5zF",
	"bWt9rs2FznJ56WuLvZ4FK/vNirfI7HdayYP7GxkZ6WkvsuWW7n66jqHph0pK/3ihoyGyzWTqHE5cSrzY",
	"KCm0Nsvc7IT+X/x6pOJXP+TrhRO0YJImTJRS33R13w0O3M6uYuAfYKik8w3thX/Oxs7ikNdW+tV70k68",
	"qDkyi/akplDqGlUOJ7Uq7U3cyDlcLbZetyr+5/ffJk01luSKoxudF95XsbArdW4CbGI4kiwXoRQYgNnY",
	"BwEfrYvYne4/25+SFJQesUoms+T5/nT/eRJCwyKc86B1UQe0jDuISX8IyEys1xB8Q8bwRiSzXkmneSND",
	"51+SH7y+sn2/ivZuzWg9hJu3NW6/qh1Opw8nAJ1t7KUkCIYi6Ju0ehQ3HVurE+6g994Xpjy7fcrgwSBM",
	"en77pM3DVhA8ZIK3zxq+PgVTqMuS2VUyS16FtGZi7CTmNA3bUS4ZC0uUc8EeydqFmdxiCECYCsWkp2HJ",
	"gxhwHjSU4A7mq4kU4d4WOAKxv6N/H2Y0xOxert6IkIz1nnM/jr/cSuFufLvt8tBbaxclu3wTP342nW4n",
	"o5S2/ywADr1Cq5k7Z8p9l7WTKW+Rc7f4Lv/ugpxWdKEmQpmBFM0La/CqvybmHwTBLymug+b8wLujFSvR",
	"Vrks+tpqFGBxwaxQ6Bw59o3Xggmw4O9jhczJhUZxDJT6A+OcvneeUqcFxVbXAN6FnxtcC/j4a4Qh5nfh",
	"PqaHzScHI79u+MOi9EMF3sDhFKJTh5hwuLT/EBOzzt8bZN/X80hBEDET3hLaY7Y6etI+aMVoy42D7iqO",
	"ru/Ms9cwLIUKG4LtArzrOXY7vjr7BZ31AGK7QDnt2f7P8L9Ht0/qfiWx+wOLkAmBoeQhFqT3BCo5p6tA",
	"tQKpRXwaqaUrKJV5+mBo+ibmlMDapy5vQHo3oETYY3oFgwwROFMK7TFooyet0D1/HiPFK/rzRqxjzqTQ",
	"4y7Evgz9TbR4O7jiijeC67bEZBdsR7tJXRRLwJ6x0JSDYGF01PwfPKyLZ++CueZVYM+hyuMdH4MUWFYm",
	"GOc6vZY7HvdWf4V4/zcf5t+PmB4KQK+RoqoGPwE3KbCRDCAlygsZfDCrinz0WD7Z/vrlV8XSL5G3bv+M",
	"5zeTt4YXqd9B2npvPB9NX9w+ofvJKk04vMOE7R8aPlhshyqftHbSuuCYW8d7aytKAfz9ktHHs/XZ+n8B",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./common.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
