// Package userapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package userapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/levonn-dev/vgkeep/libs/go/contract/common"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ProfileCard The cross-user projection of a user. Never email, never roles.
type ProfileCard = externalRef0.ProfileCard

// UpdateUserRequest Absent fields keep their value; an empty avatar_url clears it.
type UpdateUserRequest struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// Handle New typed form. Any change to the typed string, including a decoration-only edit (case or underscores only, same folded key), still consumes the cooldown: one change per cooldown window (429 handle_cooldown); folded-key collisions answer 409 handle_taken.
	Handle            *externalRef0.Handle       `json:"handle,omitempty"`
	LandingPage       *externalRef0.LandingPage  `json:"landing_page,omitempty"`
	PreferredCurrency *externalRef0.CurrencyCode `json:"preferred_currency,omitempty"`
	ProfileVisibility *externalRef0.Visibility   `json:"profile_visibility,omitempty"`
}

// UpsertUserRequest defines model for UpsertUserRequest.
type UpsertUserRequest struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// DisplayName The provider's display name. Used ONLY as the handle derivation seed when this upsert creates the account; it is not stored and never overwrites an existing handle.
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`

	// LocaleHint BCP 47 language tag from the login request's Accept-Language header. Applied only when this upsert creates the account: it seeds preferred_currency and never touches an existing user.
	LocaleHint *string `json:"locale_hint,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl *string   `json:"avatar_url,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`

	// Handle The user's single identity. 2-30 chars, alphanumeric plus interior underscores; case and underscores are decoration (uniqueness folds them).
	Handle externalRef0.Handle `json:"handle"`
	Id     openapi_types.UUID  `json:"id"`

	// LandingPage Where the app opens after sign-in. Private preference, defaulted to feed for every account; never on ProfileCard.
	LandingPage externalRef0.LandingPage `json:"landing_page"`

	// PreferredCurrency The display currency the SPA converts market values into. Defaulted from locale_hint at account creation, USD when no hint maps.
	PreferredCurrency externalRef0.CurrencyCode `json:"preferred_currency"`
	ProfileVisibility externalRef0.Visibility   `json:"profile_visibility"`
	Roles             []externalRef0.Role       `json:"roles"`
	UpdatedAt         time.Time                 `json:"updated_at"`
}

// BadRequest defines model for BadRequest.
type BadRequest = externalRef0.Problem

// Conflict defines model for Conflict.
type Conflict = externalRef0.Problem

// Forbidden defines model for Forbidden.
type Forbidden = externalRef0.Problem

// NotFound defines model for NotFound.
type NotFound = externalRef0.Problem

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = externalRef0.Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = externalRef0.Problem

// GetSharedProfilesByIdsParams defines parameters for GetSharedProfilesByIds.
type GetSharedProfilesByIdsParams struct {
	Ids []openapi_types.UUID `form:"ids" json:"ids"`
}

// SearchSharedProfilesParams defines parameters for SearchSharedProfiles.
type SearchSharedProfilesParams struct {
	Q externalRef0.UserSearchQ `form:"q" json:"q"`
}

// UpsertUserJSONRequestBody defines body for UpsertUser for application/json ContentType.
type UpsertUserJSONRequestBody = UpsertUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// UpsertUserWithBody Create-or-update a user at login time (auth service only; role `service`)
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
	UpsertUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertUser Create-or-update a user at login time (auth service only; role `service`)
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
	UpsertUser(ctx context.Context, body UpsertUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSharedProfilesByIds Batch profile cards for hydration (returned regardless of visibility - actions are signed; page access stays gated)
	//
	// Corresponds with GET /shared/profiles/by-ids (the `GetSharedProfilesByIds` operationId).
	GetSharedProfilesByIds(ctx context.Context, params *GetSharedProfilesByIdsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchSharedProfiles Substring search over listed profiles' folded handles
	//
	// Corresponds with GET /shared/profiles/search (the `SearchSharedProfiles` operationId).
	SearchSharedProfiles(ctx context.Context, params *SearchSharedProfilesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSharedProfile Resolve a handle to its profile card (any authenticated caller; non-private only)
	//
	// Corresponds with GET /shared/profiles/{handle} (the `GetSharedProfile` operationId).
	GetSharedProfile(ctx context.Context, handle string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUser Delete a user account (self only); idempotent
	//
	// Corresponds with DELETE /users/{userId} (the `DeleteUser` operationId).
	DeleteUser(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUser Fetch a user (self, or role `service`/`admin`)
	//
	// Corresponds with GET /users/{userId} (the `GetUser` operationId).
	GetUser(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateUserWithBody Self-service profile update (handle, avatar URL, currency, visibility)
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
	UpdateUserWithBody(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateUser Self-service profile update (handle, avatar URL, currency, visibility)
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
	UpdateUser(ctx context.Context, userId openapi_types.UUID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// UpsertUserWithBody Create-or-update a user at login time (auth service only; role `service`)
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
func (c *Client) UpsertUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertUser Create-or-update a user at login time (auth service only; role `service`)
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
func (c *Client) UpsertUser(ctx context.Context, body UpsertUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSharedProfilesByIds Batch profile cards for hydration (returned regardless of visibility - actions are signed; page access stays gated)
//
// Corresponds with GET /shared/profiles/by-ids (the `GetSharedProfilesByIds` operationId).
func (c *Client) GetSharedProfilesByIds(ctx context.Context, params *GetSharedProfilesByIdsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSharedProfilesByIdsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SearchSharedProfiles Substring search over listed profiles' folded handles
//
// Corresponds with GET /shared/profiles/search (the `SearchSharedProfiles` operationId).
func (c *Client) SearchSharedProfiles(ctx context.Context, params *SearchSharedProfilesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchSharedProfilesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSharedProfile Resolve a handle to its profile card (any authenticated caller; non-private only)
//
// Corresponds with GET /shared/profiles/{handle} (the `GetSharedProfile` operationId).
func (c *Client) GetSharedProfile(ctx context.Context, handle string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSharedProfileRequest(c.Server, handle)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteUser Delete a user account (self only); idempotent
//
// Corresponds with DELETE /users/{userId} (the `DeleteUser` operationId).
func (c *Client) DeleteUser(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetUser Fetch a user (self, or role `service`/`admin`)
//
// Corresponds with GET /users/{userId} (the `GetUser` operationId).
func (c *Client) GetUser(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateUserWithBody Self-service profile update (handle, avatar URL, currency, visibility)
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
func (c *Client) UpdateUserWithBody(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUserRequestWithBody(c.Server, userId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateUser Self-service profile update (handle, avatar URL, currency, visibility)
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
func (c *Client) UpdateUser(ctx context.Context, userId openapi_types.UUID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUserRequest(c.Server, userId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewUpsertUserRequest calls the generic UpsertUser builder with application/json body
func NewUpsertUserRequest(server string, body UpsertUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpsertUserRequestWithBody(server, "application/json", bodyReader)
}

// NewUpsertUserRequestWithBody constructs an http.Request for the UpsertUser method, with any body, and a specified content type
func NewUpsertUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/users/upsert")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetSharedProfilesByIdsRequest constructs an http.Request for the GetSharedProfilesByIds method
func NewGetSharedProfilesByIdsRequest(server string, params *GetSharedProfilesByIdsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/shared/profiles/by-ids")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Ids != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "ids", params.Ids, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSearchSharedProfilesRequest constructs an http.Request for the SearchSharedProfiles method
func NewSearchSharedProfilesRequest(server string, params *SearchSharedProfilesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/shared/profiles/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSharedProfileRequest constructs an http.Request for the GetSharedProfile method
func NewGetSharedProfileRequest(server string, handle string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "handle", handle, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/shared/profiles/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteUserRequest constructs an http.Request for the DeleteUser method
func NewDeleteUserRequest(server string, userId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "userId", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserRequest constructs an http.Request for the GetUser method
func NewGetUserRequest(server string, userId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "userId", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateUserRequest calls the generic UpdateUser builder with application/json body
func NewUpdateUserRequest(server string, userId openapi_types.UUID, body UpdateUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateUserRequestWithBody(server, userId, "application/json", bodyReader)
}

// NewUpdateUserRequestWithBody constructs an http.Request for the UpdateUser method, with any body, and a specified content type
func NewUpdateUserRequestWithBody(server string, userId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "userId", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// UpsertUserWithBodyWithResponse Create-or-update a user at login time (auth service only; role `service`)
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
	UpsertUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertUserResponse, error)

	// UpsertUserWithResponse Create-or-update a user at login time (auth service only; role `service`)
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
	UpsertUserWithResponse(ctx context.Context, body UpsertUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertUserResponse, error)

	// GetSharedProfilesByIdsWithResponse Batch profile cards for hydration (returned regardless of visibility - actions are signed; page access stays gated)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /shared/profiles/by-ids (the `GetSharedProfilesByIds` operationId).
	GetSharedProfilesByIdsWithResponse(ctx context.Context, params *GetSharedProfilesByIdsParams, reqEditors ...RequestEditorFn) (*GetSharedProfilesByIdsResponse, error)

	// SearchSharedProfilesWithResponse Substring search over listed profiles' folded handles
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /shared/profiles/search (the `SearchSharedProfiles` operationId).
	SearchSharedProfilesWithResponse(ctx context.Context, params *SearchSharedProfilesParams, reqEditors ...RequestEditorFn) (*SearchSharedProfilesResponse, error)

	// GetSharedProfileWithResponse Resolve a handle to its profile card (any authenticated caller; non-private only)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /shared/profiles/{handle} (the `GetSharedProfile` operationId).
	GetSharedProfileWithResponse(ctx context.Context, handle string, reqEditors ...RequestEditorFn) (*GetSharedProfileResponse, error)

	// DeleteUserWithResponse Delete a user account (self only); idempotent
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /users/{userId} (the `DeleteUser` operationId).
	DeleteUserWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteUserResponse, error)

	// GetUserWithResponse Fetch a user (self, or role `service`/`admin`)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /users/{userId} (the `GetUser` operationId).
	GetUserWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetUserResponse, error)

	// UpdateUserWithBodyWithResponse Self-service profile update (handle, avatar URL, currency, visibility)
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
	UpdateUserWithBodyWithResponse(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error)

	// UpdateUserWithResponse Self-service profile update (handle, avatar URL, currency, visibility)
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
	UpdateUserWithResponse(ctx context.Context, userId openapi_types.UUID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error)
}

type UpsertUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *User
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Forbidden
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpsertUserResponse) GetJSON200() *User {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r UpsertUserResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r UpsertUserResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r UpsertUserResponse) GetApplicationproblemJSON403() *Forbidden {
	return r.ApplicationproblemJSON403
}

// GetBody returns the raw response body bytes
func (r UpsertUserResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpsertUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpsertUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpsertUserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSharedProfilesByIdsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Profiles []ProfileCard `json:"profiles"`
	}
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetSharedProfilesByIdsResponse) GetJSON200() *struct {
	Profiles []ProfileCard `json:"profiles"`
} {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r GetSharedProfilesByIdsResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetSharedProfilesByIdsResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetBody returns the raw response body bytes
func (r GetSharedProfilesByIdsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetSharedProfilesByIdsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSharedProfilesByIdsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSharedProfilesByIdsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SearchSharedProfilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Profiles []ProfileCard `json:"profiles"`
	}
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SearchSharedProfilesResponse) GetJSON200() *struct {
	Profiles []ProfileCard `json:"profiles"`
} {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r SearchSharedProfilesResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r SearchSharedProfilesResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetBody returns the raw response body bytes
func (r SearchSharedProfilesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SearchSharedProfilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchSharedProfilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SearchSharedProfilesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSharedProfileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ProfileCard
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetSharedProfileResponse) GetJSON200() *ProfileCard {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetSharedProfileResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetSharedProfileResponse) GetApplicationproblemJSON404() *NotFound {
	return r.ApplicationproblemJSON404
}

// GetBody returns the raw response body bytes
func (r GetSharedProfileResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetSharedProfileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSharedProfileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSharedProfileResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Forbidden
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r DeleteUserResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r DeleteUserResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r DeleteUserResponse) GetApplicationproblemJSON403() *Forbidden {
	return r.ApplicationproblemJSON403
}

// GetBody returns the raw response body bytes
func (r DeleteUserResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteUserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *User
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Forbidden
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetUserResponse) GetJSON200() *User {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r GetUserResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetUserResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r GetUserResponse) GetApplicationproblemJSON403() *Forbidden {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetUserResponse) GetApplicationproblemJSON404() *NotFound {
	return r.ApplicationproblemJSON404
}

// GetBody returns the raw response body bytes
func (r GetUserResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetUserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *User
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *BadRequest
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Forbidden
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *NotFound
	// ApplicationproblemJSON409 the response for an HTTP 409 `application/problem+json` response
	ApplicationproblemJSON409 *Conflict
	// ApplicationproblemJSON429 the response for an HTTP 429 `application/problem+json` response
	ApplicationproblemJSON429 *TooManyRequests
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdateUserResponse) GetJSON200() *User {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON400() *BadRequest {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON403() *Forbidden {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON404() *NotFound {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON409 returns the response for an HTTP 409 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON409() *Conflict {
	return r.ApplicationproblemJSON409
}

// GetApplicationproblemJSON429 returns the response for an HTTP 429 `application/problem+json` response
func (r UpdateUserResponse) GetApplicationproblemJSON429() *TooManyRequests {
	return r.ApplicationproblemJSON429
}

// GetBody returns the raw response body bytes
func (r UpdateUserResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateUserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// UpsertUserWithBodyWithResponse Create-or-update a user at login time (auth service only; role `service`)
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
func (c *ClientWithResponses) UpsertUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertUserResponse, error) {
	rsp, err := c.UpsertUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertUserResponse(rsp)
}

// UpsertUserWithResponse Create-or-update a user at login time (auth service only; role `service`)
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /internal/users/upsert (the `UpsertUser` operationId).
func (c *ClientWithResponses) UpsertUserWithResponse(ctx context.Context, body UpsertUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertUserResponse, error) {
	rsp, err := c.UpsertUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertUserResponse(rsp)
}

// GetSharedProfilesByIdsWithResponse Batch profile cards for hydration (returned regardless of visibility - actions are signed; page access stays gated)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /shared/profiles/by-ids (the `GetSharedProfilesByIds` operationId).
func (c *ClientWithResponses) GetSharedProfilesByIdsWithResponse(ctx context.Context, params *GetSharedProfilesByIdsParams, reqEditors ...RequestEditorFn) (*GetSharedProfilesByIdsResponse, error) {
	rsp, err := c.GetSharedProfilesByIds(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSharedProfilesByIdsResponse(rsp)
}

// SearchSharedProfilesWithResponse Substring search over listed profiles' folded handles
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /shared/profiles/search (the `SearchSharedProfiles` operationId).
func (c *ClientWithResponses) SearchSharedProfilesWithResponse(ctx context.Context, params *SearchSharedProfilesParams, reqEditors ...RequestEditorFn) (*SearchSharedProfilesResponse, error) {
	rsp, err := c.SearchSharedProfiles(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchSharedProfilesResponse(rsp)
}

// GetSharedProfileWithResponse Resolve a handle to its profile card (any authenticated caller; non-private only)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /shared/profiles/{handle} (the `GetSharedProfile` operationId).
func (c *ClientWithResponses) GetSharedProfileWithResponse(ctx context.Context, handle string, reqEditors ...RequestEditorFn) (*GetSharedProfileResponse, error) {
	rsp, err := c.GetSharedProfile(ctx, handle, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSharedProfileResponse(rsp)
}

// DeleteUserWithResponse Delete a user account (self only); idempotent
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /users/{userId} (the `DeleteUser` operationId).
func (c *ClientWithResponses) DeleteUserWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteUserResponse, error) {
	rsp, err := c.DeleteUser(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserResponse(rsp)
}

// GetUserWithResponse Fetch a user (self, or role `service`/`admin`)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /users/{userId} (the `GetUser` operationId).
func (c *ClientWithResponses) GetUserWithResponse(ctx context.Context, userId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetUserResponse, error) {
	rsp, err := c.GetUser(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserResponse(rsp)
}

// UpdateUserWithBodyWithResponse Self-service profile update (handle, avatar URL, currency, visibility)
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
func (c *ClientWithResponses) UpdateUserWithBodyWithResponse(ctx context.Context, userId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	rsp, err := c.UpdateUserWithBody(ctx, userId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUserResponse(rsp)
}

// UpdateUserWithResponse Self-service profile update (handle, avatar URL, currency, visibility)
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /users/{userId} (the `UpdateUser` operationId).
func (c *ClientWithResponses) UpdateUserWithResponse(ctx context.Context, userId openapi_types.UUID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	rsp, err := c.UpdateUser(ctx, userId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUserResponse(rsp)
}

// ParseUpsertUserResponse parses an HTTP response from a UpsertUserWithResponse call
func ParseUpsertUserResponse(rsp *http.Response) (*UpsertUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpsertUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	}

	return response, nil
}

// ParseGetSharedProfilesByIdsResponse parses an HTTP response from a GetSharedProfilesByIdsWithResponse call
func ParseGetSharedProfilesByIdsResponse(rsp *http.Response) (*GetSharedProfilesByIdsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSharedProfilesByIdsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Profiles []ProfileCard `json:"profiles"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	}

	return response, nil
}

// ParseSearchSharedProfilesResponse parses an HTTP response from a SearchSharedProfilesWithResponse call
func ParseSearchSharedProfilesResponse(rsp *http.Response) (*SearchSharedProfilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchSharedProfilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Profiles []ProfileCard `json:"profiles"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	}

	return response, nil
}

// ParseGetSharedProfileResponse parses an HTTP response from a GetSharedProfileWithResponse call
func ParseGetSharedProfileResponse(rsp *http.Response) (*GetSharedProfileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSharedProfileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProfileCard
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	}

	return response, nil
}

// ParseDeleteUserResponse parses an HTTP response from a DeleteUserWithResponse call
func ParseDeleteUserResponse(rsp *http.Response) (*DeleteUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	}

	return response, nil
}

// ParseGetUserResponse parses an HTTP response from a GetUserWithResponse call
func ParseGetUserResponse(rsp *http.Response) (*GetUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	}

	return response, nil
}

// ParseUpdateUserResponse parses an HTTP response from a UpdateUserWithResponse call
func ParseUpdateUserResponse(rsp *http.Response) (*UpdateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fprb9y41f4rB3wXiI1Xc4lttJvxh4XjRdoU2awbx1l0U3dCi2dGXFOkQlLjaI3578UhpRlpRr4h2Tgt",
	"+inRUCTP5TnPucjXLDV5YTRq79jkmhXc8hw92vCUmjw3elo6tKfIbZr9nX6Vmk3YxxJtxRKmeY70yBJm",
	"8WMpLQo28bbEhLk0w5zTjpx/eoV67jM2+dNBwnKpm8enCfNVQSc4b6Wes+VySSe5wmiHQYjnXLzBjyU6",
	"H0XSHnX4Ly8KJVPupdGjwpoLhfn//+aMprX13d9ZnLEJ+7/RWtFRXHWjWr+TuDneLdClVhZ0Kpuwd1xJ",
	"Ea6AGZeqtAg7qREIUi9oaXphRHUIAj2XCsgYDnyGMJOoxC5bJuzY6JmS6WMIf6SNz9ACT1NTag/mSpN0",
	"3EPGtVD4xMHMKIECLrGq9YorU88vUQf5Xxh7IYVA/QgKvNSunM1kKlF7sEYhCfTa+Bem1OIR5HltPMzC",
	"3cuEvTXmJ66rGpvuEcT5a/AVpBnXcxTgjQGLKWqvNryZGqOEuYoOPdO89Jmx8nd8DBv+JJ2Tej6qAwi8",
	"uUTN6L36DLrixJqZVHjMbRCxe8LbDCG1xrkBERMU1vyGaQhRMwMO9OMQXuMCLWDOpUpAhwcCkBuyhBXW",
	"FGi9jPzCF9xzOy2toqcNNkpYNOE99Y4eoW1F1GC6kE5eSCV9dc8j3q03LBNGykxlMMLM2Jx7NmFlKQXb",
	"5s02Ab9fbVwp0CvS+eoYc0FGDPgoBPd45tC2aHeDWC4cRWQgOQeXiAWRnrSw4KrEQ+AaMC98BWvbQqqQ",
	"WwfS3+WBVrLYGx98n9zmEq7UzzM2ef8g55xvhTVeAV0igGw8hCNd1UEF3gQ6j6tRggSkTlUppJ4DB4Gp",
	"sSFiBkarClBIDzspdwjGQqkFWpcaiw5oOQHHc2yx7m4CzkulIDXalU32aOJ1AkY38Q0F2tUCXEktzBXs",
	"HOw92wryw/r8AbF6apSSThrtgGt3hRYOxs86LD/8pyajKq5JpWnB5/dF+6u45YR2BMjjDK1FMU1La1Gn",
	"94X8cf36sRFfLnaWvdB2aP0GtD8Pi0K6QvFqGuugPqoqrFlIgfaJg/rlUCcM4cyhgJ9fv/oH8Oj26BUQ",
	"aOUi1hwOUcBVhhp8Jh2UQX5ILXJfQ6XO7YcgPUgH2nhw3lgUwLWoic8s0F5ZSVsoMj9J5wm88Tpyf49e",
	"gTl7CVGZlCucZlL3MMPz4xM4+DMoruclp/jhc5hZkwdZlZlLDTaa/omDozTFwg9eNS9nyAVx9xGlIRQh",
	"Yu6l/YS0J1s52AZhyxDelGm2YYWQLoINNqrU2/k12mfD/7106tDeBbMtG0cdxZT7DvMTMQ+8zPFhHvvS",
	"fEmoJrM9cUCpXCFIgdpLXw1hb7A/JsayLgGuiozrMkcrUyhU6UBqj1Z2ifEQAluSl9p0yS22yBV2Si0/",
	"lqjRxaI1+D/frcnrXhlym+MeZI4O223Z5JcMLUZMFgWYAolwZx4tODnXA6mHcBLCGmuIok4xAYEzXiof",
	"qjeYYUxBQGCt1qFdR7GGVllUK97PuQ/Sq8u+vc5ueGsVUqTn6ckRZa0FWu8g5/YSfcz/wc1mCD+udAsM",
	"0OIN4H7VlASoS6MTODv9MUa7NhDeynnhVnp+kXIqlIChh/WYu3se8aZuPGo4cWt5rM1CofSQIN3gkADS",
	"hkhuK9MawXv9vQHrDnl0hOxjpz4MhDGA92jJ/f96fzT49fx6f/ldX0B1maKbMPfHnU5/L+mcyge/Hw1+",
	"HQ+ene/8MFk/Tc+vx8ne98vW+u4Pt13djsrJNUNd5mRaKntiU8ASRnFFlv5UKGPbLL11WtO3bPF1Whtm",
	"O/+Hzr93SWrnuU779znPfelaS0SNc7QBaNKr/l3xh+s7cBVWm2NWV93i/v+1W4/XbrVJpgVgOpAljItc",
	"6tsQ+66jcLO7iKmG4l8r6XzAf/2f8z5dHKallb46JetER10gt2iPSgreG0zZ3dSYtLVxLWf3tPj0ojHx",
	"3355y+r+n+SKq2ubZ94XcZQg9cwE2MQIYYt5aD4DMB3ahUxJ5wVaF7E7Hj4djkkKSsi8kGzC9ofj4T4L",
	"ZJQFPUehKNFcjegYN4plZqAAEzsEgm/IUS8Fm7SaiHrmic4/N6K6ZZbysBnKdpey7MLN2xI3p6R74/GX",
	"E4B06xndRMFQBHuTVQ/ipX1nrYQbtea3YcvTu7d0RlRh0/7dm9aDygDoMs+5rdiEHYd0ODB2EHNhzVlU",
	"g8SGhHI17NCNDYZC53EYGAw+1L992A3njlzGLYpRHd1udFENpAgumGMPWv6C/jTsqDnWPa9eipDJW5P2",
	"9/1DdRlevHmsvipi7ix8c/7pZXz56Xi8WclQzfdZWOoSfGOZe5dZ7eyzVWZt8Ozq8G0q3cYrnehCQU31",
	"qhT18Du0fl8Pvh0wPuc+zaDWAtKVgFklmkbHoi+tRgEW59wKRR2PmcE6jcAAeEjAsUmi/gLFIVD1R1U1",
	"ve88rxzMqfK7AbYufM+5Ebbxc08Xudug7TPD+pVRz+ej/1qsnRXUwe2NIWZZyMnR6JL2LM5Y8TV5swO8",
	"0/Ii0gFEz4ehUCNso+mTZjIZixjXD53ruLq8N+fdwHaUgddkt6qbbua7zbLl/A/MgR2gbLv7pBXBn5HW",
	"Du7etPrctYU4fanNlQZDNXmcLOwIVPKCXIGqAqlFnHGV0mX8QuHuBibeoDNqQQmxnjx6A9K7Dj3BDtcV",
	"kNyoPZkSBaRcKbSHoI0eNFdTxqypJpZR1/TPS7GMDYVCj9tA+TH8XpdSd0MknngrRO6q2rchc7Dd8USx",
	"BOwYC1xZ5KKCudG4+x9T80QNVpVOPWrZcahm0VOHIAXmhQmBskxujOPH9c1XKGm/8Ur2oSTRhcELpGqj",
	"RkHwfkJ00a1rRx9Ck/khoLugtNXX8zTfBL8qGP6I3mrz4+Y301uFOd0331o9GJC04dndG1Z/JkMb9u6x",
	"YfPPLzbKHVSzQdPNNfms7v92YrZL6q/TcPbmVbIabSetQns3OqoZcwS0t+cY78+X58t/BwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./common.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
