// Command domaingen reads api/domain.yaml - the cross-language region
// and platform tables - and emits a generated Go file for
// libs/go/regionkit and a generated TypeScript file for the frontend.
// One source of truth, two languages; `task gen` (via `task
// gen:domain`) runs this on every codegen pass, and CI's drift check
// fails if a hand edit to either output ever diverges from it.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// domain is api/domain.yaml's parsed shape. Field order within each
// slice is document order (yaml.v3 preserves sequence order on
// decode), which both emitters rely on for deterministic,
// declaration-ordered output.
type domain struct {
	Regions        []regionRow        `yaml:"regions"`
	JPConsoleNames []string           `yaml:"jp_console_names"`
	Platforms      []platformRow      `yaml:"platforms"`
	ReleaseRegions []releaseRegionRow `yaml:"release_regions"`
}

// regionRow is one entry in domain.yaml's regions list. LocalizationChain
// is nil/empty for a region with no localized bundles (ntsc_u,
// region_free today) - both emitters skip such a region's row in the
// localization-chains table rather than emitting an empty chain.
type regionRow struct {
	Name              string   `yaml:"name"`
	Class             string   `yaml:"class"`
	LocalizationChain []string `yaml:"localization_chain"`
}

// platformRow is one entry in domain.yaml's platforms list. Name is
// descriptive only (not part of either generated table's data); a
// TwinIGDBID of 0 means the platform has no JP-regional twin (the
// yaml omits the field entirely for such a row).
type platformRow struct {
	IGDBID     int64  `yaml:"igdb_id"`
	Name       string `yaml:"name"`
	Region     string `yaml:"region"`
	TwinIGDBID int64  `yaml:"twin_igdb_id"`
}

// releaseRegionRow is one entry in domain.yaml's release_regions list:
// IGDB's release_region vendor enum (the id an IGDB release_dates or
// release_regions row carries on the wire) decoded to its canonical
// name. EntryRegion is the collector's-entry region a release in that
// region badges as, for a region with a direct 1:1 mapping; empty for
// a row with none (worldwide today - it expands to more than one
// entry region instead of picking one, a decision only the consuming
// picker can make), same convention as platformRow's TwinIGDBID: the
// yaml omits the field entirely for such a row.
type releaseRegionRow struct {
	IGDBID      int    `yaml:"igdb_id"`
	Name        string `yaml:"name"`
	EntryRegion string `yaml:"entry_region"`
}

// parseDomain decodes domain.yaml. KnownFields is on: an unrecognized
// key (a typo'd field name) fails the parse instead of silently
// vanishing, since a swallowed typo would defeat the whole point of a
// single generated source of truth.
func parseDomain(data []byte) (*domain, error) {
	dec := yaml.NewDecoder(bytes.NewReader(data))
	dec.KnownFields(true)
	var d domain
	if err := dec.Decode(&d); err != nil {
		return nil, fmt.Errorf("parsing domain yaml: %w", err)
	}
	return &d, nil
}

// generateGo renders libs/go/regionkit/tables_gen.go for package pkg.
// The raw source is built as plain text, then run through go/format
// so map-literal alignment and spacing are always canonical gofmt
// output regardless of how domain.yaml's row count or column widths
// change - the generator never hand-predicts gofmt's formatting.
func generateGo(d *domain, pkg string) ([]byte, error) {
	var b strings.Builder

	b.WriteString("// Code generated by domaingen from api/domain.yaml. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import \"strings\"\n\n")

	b.WriteString("// RegionNames lists every region api/domain.yaml declares, in\n// declaration order.\n")
	b.WriteString("var RegionNames = []string{")
	for i, r := range d.Regions {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", r.Name)
	}
	b.WriteString("}\n\n")

	b.WriteString("// regionClassTable backs RegionClass.\n")
	b.WriteString("var regionClassTable = map[string]string{\n")
	for _, r := range d.Regions {
		fmt.Fprintf(&b, "\t%q: %q,\n", r.Name, r.Class)
	}
	b.WriteString("}\n\n")

	b.WriteString("// RegionClass maps a known entry region onto the console-listing\n")
	b.WriteString("// class that prices it, mirroring api/domain.yaml's regions[].class;\n")
	b.WriteString("// an unrecognized region defaults to \"base\".\n")
	b.WriteString("func RegionClass(region string) string {\n")
	b.WriteString("\tif c, ok := regionClassTable[region]; ok {\n\t\treturn c\n\t}\n")
	b.WriteString("\treturn \"base\"\n}\n\n")

	b.WriteString("// LocalizationChains maps an entry region to its ordered IGDB\n")
	b.WriteString("// localization identifiers; a region with no chain is absent from\n")
	b.WriteString("// this map.\n")
	b.WriteString("var LocalizationChains = map[string][]string{\n")
	for _, r := range d.Regions {
		if len(r.LocalizationChain) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t%q: {", r.Name)
		for i, id := range r.LocalizationChain {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", id)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("// JPConsoleNames are PriceCharting's distinct-name JP market consoles\n")
	b.WriteString("// (the ones filed without a \"jp \" prefix).\n")
	b.WriteString("var JPConsoleNames = map[string]bool{\n")
	for _, n := range d.JPConsoleNames {
		fmt.Fprintf(&b, "\t%q: true,\n", n)
	}
	b.WriteString("}\n\n")

	b.WriteString("// ConsoleRegion classifies a PriceCharting console-name into the\n")
	b.WriteString("// region class its listings price: \"pal \" prefix, \"jp \" prefix or a\n")
	b.WriteString("// distinct JP market name, else base.\n")
	b.WriteString("func ConsoleRegion(consoleName string) string {\n")
	b.WriteString("\tc := strings.ToLower(strings.TrimSpace(consoleName))\n")
	b.WriteString("\tswitch {\n")
	b.WriteString("\tcase strings.HasPrefix(c, \"pal \"):\n\t\treturn \"pal\"\n")
	b.WriteString("\tcase strings.HasPrefix(c, \"jp \"), JPConsoleNames[c]:\n\t\treturn \"jp\"\n")
	b.WriteString("\tdefault:\n\t\treturn \"base\"\n")
	b.WriteString("\t}\n}\n\n")

	b.WriteString("// PlatformRegions maps an IGDB platform id to the entry region its\n")
	b.WriteString("// releases belong to.\n")
	b.WriteString("var PlatformRegions = map[int64]string{\n")
	for _, p := range d.Platforms {
		fmt.Fprintf(&b, "\t%d: %q,\n", p.IGDBID, p.Region)
	}
	b.WriteString("}\n\n")

	b.WriteString("// TwinPlatformIDs pairs an IGDB platform id with its JP-regional twin\n")
	b.WriteString("// in both directions: looking up either side of a pair returns the\n")
	b.WriteString("// other.\n")
	b.WriteString("var TwinPlatformIDs = map[int64]int64{\n")
	for _, p := range d.Platforms {
		if p.TwinIGDBID == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t%d: %d,\n", p.IGDBID, p.TwinIGDBID)
		fmt.Fprintf(&b, "\t%d: %d,\n", p.TwinIGDBID, p.IGDBID)
	}
	b.WriteString("}\n\n")

	b.WriteString("// ReleaseRegionNames maps IGDB's release_region vendor enum onto its\n")
	b.WriteString("// canonical name; an id absent from this map is unknown to this service.\n")
	b.WriteString("var ReleaseRegionNames = map[int]string{\n")
	for _, r := range d.ReleaseRegions {
		fmt.Fprintf(&b, "\t%d: %q,\n", r.IGDBID, r.Name)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated Go: %w", err)
	}
	return formatted, nil
}

// tsString renders s as a single-quoted TS string literal, escaping
// backslashes and single quotes. domain.yaml's values are reviewed
// identifiers and short names, not arbitrary text, but a generator
// that emits unescaped string literals is one stray apostrophe away
// from silently producing broken TS, so escaping stays correct
// regardless of what the source data looks like.
func tsString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `'`, `\'`)
	return "'" + s + "'"
}

// generateTS renders frontend/src/gen/domain.ts. Unlike generateGo,
// there is no stdlib formatter to normalize the output through, so
// the builder emits already-canonical (2-space indented, single-
// quoted) TypeScript directly.
func generateTS(d *domain) ([]byte, error) {
	var b strings.Builder

	b.WriteString("// Code generated by domaingen from api/domain.yaml. DO NOT EDIT.\n\n")

	b.WriteString("export const REGIONS = [")
	for i, r := range d.Regions {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(tsString(r.Name))
	}
	b.WriteString("] as const\n\n")

	b.WriteString("export type Region = (typeof REGIONS)[number]\n\n")

	b.WriteString("export const REGION_CLASS: Record<string, 'base' | 'jp' | 'pal'> = {\n")
	for _, r := range d.Regions {
		fmt.Fprintf(&b, "  %s: %s,\n", r.Name, tsString(r.Class))
	}
	b.WriteString("}\n\n")

	b.WriteString("export const LOCALIZATION_CHAINS: Record<string, string[]> = {\n")
	for _, r := range d.Regions {
		if len(r.LocalizationChain) == 0 {
			continue
		}
		fmt.Fprintf(&b, "  %s: [", r.Name)
		for i, id := range r.LocalizationChain {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(tsString(id))
		}
		b.WriteString("],\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("export const JP_CONSOLE_NAMES = new Set([")
	for i, n := range d.JPConsoleNames {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(tsString(n))
	}
	b.WriteString("])\n\n")

	b.WriteString("export function consoleRegionFor(consoleName: string): 'ntsc_u' | 'ntsc_j' | 'pal' {\n")
	b.WriteString("  const c = consoleName.trim().toLowerCase()\n")
	b.WriteString("  if (c.startsWith('pal ')) return 'pal'\n")
	b.WriteString("  if (c.startsWith('jp ') || JP_CONSOLE_NAMES.has(c)) return 'ntsc_j'\n")
	b.WriteString("  return 'ntsc_u'\n")
	b.WriteString("}\n\n")

	b.WriteString("export const REGION_PLATFORMS: Record<number, Region> = {\n")
	for _, p := range d.Platforms {
		fmt.Fprintf(&b, "  %d: %s,\n", p.IGDBID, tsString(p.Region))
	}
	b.WriteString("}\n\n")

	b.WriteString("export const AVAILABILITY_REGIONS: Record<string, 'ntsc_u' | 'ntsc_j' | 'pal' | 'korea' | 'brazil' | 'china'> = {\n")
	for _, r := range d.ReleaseRegions {
		if r.EntryRegion == "" {
			continue
		}
		fmt.Fprintf(&b, "  %s: %s,\n", r.Name, tsString(r.EntryRegion))
	}
	b.WriteString("}\n")

	return []byte(b.String()), nil
}

func main() {
	yamlPath := flag.String("yaml", "", "path to api/domain.yaml")
	goOut := flag.String("go-out", "", "output path for the generated Go file")
	goPackage := flag.String("go-package", "regionkit", "package name for the generated Go file")
	tsOut := flag.String("ts-out", "", "output path for the generated TypeScript file")
	flag.Parse()

	if *yamlPath == "" || *goOut == "" || *tsOut == "" {
		fmt.Fprintln(os.Stderr, "usage: domaingen -yaml <path> -go-out <path> -ts-out <path> [-go-package <name>]")
		os.Exit(2)
	}

	if err := run(*yamlPath, *goOut, *goPackage, *tsOut); err != nil {
		fmt.Fprintln(os.Stderr, "domaingen:", err)
		os.Exit(1)
	}
}

func run(yamlPath, goOut, goPackage, tsOut string) error {
	data, err := os.ReadFile(yamlPath) //nolint:gosec // G304: yamlPath is a caller-supplied CLI flag (api/domain.yaml by convention); this is a codegen tool run by developers/CI, not a service handling untrusted input.
	if err != nil {
		return fmt.Errorf("reading %s: %w", yamlPath, err)
	}

	d, err := parseDomain(data)
	if err != nil {
		return err
	}

	goSrc, err := generateGo(d, goPackage)
	if err != nil {
		return err
	}
	tsSrc, err := generateTS(d)
	if err != nil {
		return err
	}

	if err := writeFile(goOut, goSrc); err != nil {
		return err
	}
	return writeFile(tsOut, tsSrc)
}

// writeFile creates the destination's parent directory (frontend/src/gen
// does not exist until the first generator run) before writing.
func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("creating directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}
