apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-pg-credentials
  labels: {{- include "user.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: user-pg-credentials
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.secretStore.passwordKey }}
