apiVersion: v1
kind: Service
metadata:
  name: user
  labels: {{- include "user.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: user
  ports:
    - { name: http, port: 8080, targetPort: http }
