// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AcceptedStatus.
const (
	Started AcceptedStatus = "started"
)

// Valid indicates whether the value is a known member of the AcceptedStatus enum.
func (e AcceptedStatus) Valid() bool {
	switch e {
	case Started:
		return true
	default:
		return false
	}
}

// Defines values for ActivityVerb.
const (
	CommentedShelf ActivityVerb = "commented_shelf"
	FollowedUser   ActivityVerb = "followed_user"
	LikedShelf     ActivityVerb = "liked_shelf"
	PublishedShelf ActivityVerb = "published_shelf"
)

// Valid indicates whether the value is a known member of the ActivityVerb enum.
func (e ActivityVerb) Valid() bool {
	switch e {
	case CommentedShelf:
		return true
	case FollowedUser:
		return true
	case LikedShelf:
		return true
	case PublishedShelf:
		return true
	default:
		return false
	}
}

// Defines values for CatalogProvider.
const (
	Igdb          CatalogProvider = "igdb"
	Pricecharting CatalogProvider = "pricecharting"
)

// Valid indicates whether the value is a known member of the CatalogProvider enum.
func (e CatalogProvider) Valid() bool {
	switch e {
	case Igdb:
		return true
	case Pricecharting:
		return true
	default:
		return false
	}
}

// Defines values for EntrySource.
const (
	Epic   EntrySource = "epic"
	Manual EntrySource = "manual"
	Psn    EntrySource = "psn"
	Steam  EntrySource = "steam"
)

// Valid indicates whether the value is a known member of the EntrySource enum.
func (e EntrySource) Valid() bool {
	switch e {
	case Epic:
		return true
	case Manual:
		return true
	case Psn:
		return true
	case Steam:
		return true
	default:
		return false
	}
}

// Defines values for EntryCreateMatchProvenance.
const (
	EntryCreateMatchProvenanceAuto EntryCreateMatchProvenance = "auto"
	EntryCreateMatchProvenanceUser EntryCreateMatchProvenance = "user"
)

// Valid indicates whether the value is a known member of the EntryCreateMatchProvenance enum.
func (e EntryCreateMatchProvenance) Valid() bool {
	switch e {
	case EntryCreateMatchProvenanceAuto:
		return true
	case EntryCreateMatchProvenanceUser:
		return true
	default:
		return false
	}
}

// Defines values for EntryCreateMediaType.
const (
	EntryCreateMediaTypePhysical EntryCreateMediaType = "physical"
)

// Valid indicates whether the value is a known member of the EntryCreateMediaType enum.
func (e EntryCreateMediaType) Valid() bool {
	switch e {
	case EntryCreateMediaTypePhysical:
		return true
	default:
		return false
	}
}

// Defines values for EntryStatus.
const (
	Backlog   EntryStatus = "backlog"
	Beaten    EntryStatus = "beaten"
	Completed EntryStatus = "completed"
	Dropped   EntryStatus = "dropped"
	Playing   EntryStatus = "playing"
	Shelved   EntryStatus = "shelved"
)

// Valid indicates whether the value is a known member of the EntryStatus enum.
func (e EntryStatus) Valid() bool {
	switch e {
	case Backlog:
		return true
	case Beaten:
		return true
	case Completed:
		return true
	case Dropped:
		return true
	case Playing:
		return true
	case Shelved:
		return true
	default:
		return false
	}
}

// Defines values for ItemCondition.
const (
	Acceptable ItemCondition = "acceptable"
	Good       ItemCondition = "good"
	Mint       ItemCondition = "mint"
	NearMint   ItemCondition = "near_mint"
	Poor       ItemCondition = "poor"
	VeryGood   ItemCondition = "very_good"
)

// Valid indicates whether the value is a known member of the ItemCondition enum.
func (e ItemCondition) Valid() bool {
	switch e {
	case Acceptable:
		return true
	case Good:
		return true
	case Mint:
		return true
	case NearMint:
		return true
	case Poor:
		return true
	case VeryGood:
		return true
	default:
		return false
	}
}

// Defines values for ItemType.
const (
	ItemTypeAccessory ItemType = "accessory"
	ItemTypeConsole   ItemType = "console"
	ItemTypeGame      ItemType = "game"
)

// Valid indicates whether the value is a known member of the ItemType enum.
func (e ItemType) Valid() bool {
	switch e {
	case ItemTypeAccessory:
		return true
	case ItemTypeConsole:
		return true
	case ItemTypeGame:
		return true
	default:
		return false
	}
}

// Defines values for LandingPage.
const (
	Collection LandingPage = "collection"
	Explore    LandingPage = "explore"
	Feed       LandingPage = "feed"
)

// Valid indicates whether the value is a known member of the LandingPage enum.
func (e LandingPage) Valid() bool {
	switch e {
	case Collection:
		return true
	case Explore:
		return true
	case Feed:
		return true
	default:
		return false
	}
}

// Defines values for MediaType.
const (
	MediaTypeDigital  MediaType = "digital"
	MediaTypePhysical MediaType = "physical"
)

// Valid indicates whether the value is a known member of the MediaType enum.
func (e MediaType) Valid() bool {
	switch e {
	case MediaTypeDigital:
		return true
	case MediaTypePhysical:
		return true
	default:
		return false
	}
}

// Defines values for Packaging.
const (
	Cib    Packaging = "cib"
	Loose  Packaging = "loose"
	Sealed Packaging = "sealed"
)

// Valid indicates whether the value is a known member of the Packaging enum.
func (e Packaging) Valid() bool {
	switch e {
	case Cib:
		return true
	case Loose:
		return true
	case Sealed:
		return true
	default:
		return false
	}
}

// Defines values for PricingMode.
const (
	PricingModeAuto     PricingMode = "auto"
	PricingModeCustom   PricingMode = "custom"
	PricingModeDisabled PricingMode = "disabled"
	PricingModeProxy    PricingMode = "proxy"
)

// Valid indicates whether the value is a known member of the PricingMode enum.
func (e PricingMode) Valid() bool {
	switch e {
	case PricingModeAuto:
		return true
	case PricingModeCustom:
		return true
	case PricingModeDisabled:
		return true
	case PricingModeProxy:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	CapExceeded               ProblemCode = "cap_exceeded"
	CommentNotFound           ProblemCode = "comment_not_found"
	ConflictingOrder          ProblemCode = "conflicting_order"
	EmailUnverified           ProblemCode = "email_unverified"
	EnrichmentUnavailable     ProblemCode = "enrichment_unavailable"
	EntryNotCustom            ProblemCode = "entry_not_custom"
	EntryNotFound             ProblemCode = "entry_not_found"
	Forbidden                 ProblemCode = "forbidden"
	HandleCooldown            ProblemCode = "handle_cooldown"
	HandleTaken               ProblemCode = "handle_taken"
	IdentityAlreadyLinked     ProblemCode = "identity_already_linked"
	IdentityNotFound          ProblemCode = "identity_not_found"
	IdentityTaken             ProblemCode = "identity_taken"
	Internal                  ProblemCode = "internal"
	InvalidBody               ProblemCode = "invalid_body"
	InvalidCallback           ProblemCode = "invalid_callback"
	InvalidInternalToken      ProblemCode = "invalid_internal_token"
	InvalidParam              ProblemCode = "invalid_param"
	InvalidProductChange      ProblemCode = "invalid_product_change"
	InvalidRefresh            ProblemCode = "invalid_refresh"
	InvalidState              ProblemCode = "invalid_state"
	InvalidToken              ProblemCode = "invalid_token"
	LastIdentity              ProblemCode = "last_identity"
	LinkEmailUnverified       ProblemCode = "link_email_unverified"
	LinkFailed                ProblemCode = "link_failed"
	MissingToken              ProblemCode = "missing_token"
	NotFound                  ProblemCode = "not_found"
	NotInBacklog              ProblemCode = "not_in_backlog"
	NotReady                  ProblemCode = "not_ready"
	OriginForbidden           ProblemCode = "origin_forbidden"
	ProductMatched            ProblemCode = "product_matched"
	ProductNotCommunity       ProblemCode = "product_not_community"
	ProductNotFound           ProblemCode = "product_not_found"
	ProductNotProvider        ProblemCode = "product_not_provider"
	ProductReferenced         ProblemCode = "product_referenced"
	ProfileNotFound           ProblemCode = "profile_not_found"
	ProviderError             ProblemCode = "provider_error"
	RefreshInProgress         ProblemCode = "refresh_in_progress"
	RefreshReused             ProblemCode = "refresh_reused"
	RematchInProgress         ProblemCode = "rematch_in_progress"
	SelfFollow                ProblemCode = "self_follow"
	ShelfNotFound             ProblemCode = "shelf_not_found"
	SubmissionNotFound        ProblemCode = "submission_not_found"
	SubmissionPending         ProblemCode = "submission_pending"
	SubmissionRateLimited     ProblemCode = "submission_rate_limited"
	SubmissionResolved        ProblemCode = "submission_resolved"
	TagCapExceeded            ProblemCode = "tag_cap_exceeded"
	TagExists                 ProblemCode = "tag_exists"
	TagNotFound               ProblemCode = "tag_not_found"
	TooManyPendingSubmissions ProblemCode = "too_many_pending_submissions"
	Unauthenticated           ProblemCode = "unauthenticated"
	UnknownFixture            ProblemCode = "unknown_fixture"
	UnknownGame               ProblemCode = "unknown_game"
	UnknownPcProduct          ProblemCode = "unknown_pc_product"
	UnknownPricingProduct     ProblemCode = "unknown_pricing_product"
	UnknownProduct            ProblemCode = "unknown_product"
	UnknownProvider           ProblemCode = "unknown_provider"
	UpstreamError             ProblemCode = "upstream_error"
	UpstreamUnavailable       ProblemCode = "upstream_unavailable"
	UserNotFound              ProblemCode = "user_not_found"
	UserServiceError          ProblemCode = "user_service_error"
	UserUnavailable           ProblemCode = "user_unavailable"
	ViewExists                ProblemCode = "view_exists"
	ViewNotFound              ProblemCode = "view_not_found"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case CapExceeded:
		return true
	case CommentNotFound:
		return true
	case ConflictingOrder:
		return true
	case EmailUnverified:
		return true
	case EnrichmentUnavailable:
		return true
	case EntryNotCustom:
		return true
	case EntryNotFound:
		return true
	case Forbidden:
		return true
	case HandleCooldown:
		return true
	case HandleTaken:
		return true
	case IdentityAlreadyLinked:
		return true
	case IdentityNotFound:
		return true
	case IdentityTaken:
		return true
	case Internal:
		return true
	case InvalidBody:
		return true
	case InvalidCallback:
		return true
	case InvalidInternalToken:
		return true
	case InvalidParam:
		return true
	case InvalidProductChange:
		return true
	case InvalidRefresh:
		return true
	case InvalidState:
		return true
	case InvalidToken:
		return true
	case LastIdentity:
		return true
	case LinkEmailUnverified:
		return true
	case LinkFailed:
		return true
	case MissingToken:
		return true
	case NotFound:
		return true
	case NotInBacklog:
		return true
	case NotReady:
		return true
	case OriginForbidden:
		return true
	case ProductMatched:
		return true
	case ProductNotCommunity:
		return true
	case ProductNotFound:
		return true
	case ProductNotProvider:
		return true
	case ProductReferenced:
		return true
	case ProfileNotFound:
		return true
	case ProviderError:
		return true
	case RefreshInProgress:
		return true
	case RefreshReused:
		return true
	case RematchInProgress:
		return true
	case SelfFollow:
		return true
	case ShelfNotFound:
		return true
	case SubmissionNotFound:
		return true
	case SubmissionPending:
		return true
	case SubmissionRateLimited:
		return true
	case SubmissionResolved:
		return true
	case TagCapExceeded:
		return true
	case TagExists:
		return true
	case TagNotFound:
		return true
	case TooManyPendingSubmissions:
		return true
	case Unauthenticated:
		return true
	case UnknownFixture:
		return true
	case UnknownGame:
		return true
	case UnknownPcProduct:
		return true
	case UnknownPricingProduct:
		return true
	case UnknownProduct:
		return true
	case UnknownProvider:
		return true
	case UpstreamError:
		return true
	case UpstreamUnavailable:
		return true
	case UserNotFound:
		return true
	case UserServiceError:
		return true
	case UserUnavailable:
		return true
	case ViewExists:
		return true
	case ViewNotFound:
		return true
	default:
		return false
	}
}

// Defines values for ProductOrigin.
const (
	Community ProductOrigin = "community"
)

// Valid indicates whether the value is a known member of the ProductOrigin enum.
func (e ProductOrigin) Valid() bool {
	switch e {
	case Community:
		return true
	default:
		return false
	}
}

// Defines values for ProductType.
const (
	ProductTypeAccessory ProductType = "accessory"
	ProductTypeConsole   ProductType = "console"
	ProductTypeGame      ProductType = "game"
	ProductTypePcListing ProductType = "pc_listing"
)

// Valid indicates whether the value is a known member of the ProductType enum.
func (e ProductType) Valid() bool {
	switch e {
	case ProductTypeAccessory:
		return true
	case ProductTypeConsole:
		return true
	case ProductTypeGame:
		return true
	case ProductTypePcListing:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseRegion.
const (
	Asia         ReleaseRegion = "asia"
	Australia    ReleaseRegion = "australia"
	Brazil       ReleaseRegion = "brazil"
	China        ReleaseRegion = "china"
	Europe       ReleaseRegion = "europe"
	Japan        ReleaseRegion = "japan"
	Korea        ReleaseRegion = "korea"
	NewZealand   ReleaseRegion = "new_zealand"
	NorthAmerica ReleaseRegion = "north_america"
	Worldwide    ReleaseRegion = "worldwide"
)

// Valid indicates whether the value is a known member of the ReleaseRegion enum.
func (e ReleaseRegion) Valid() bool {
	switch e {
	case Asia:
		return true
	case Australia:
		return true
	case Brazil:
		return true
	case China:
		return true
	case Europe:
		return true
	case Japan:
		return true
	case Korea:
		return true
	case NewZealand:
		return true
	case NorthAmerica:
		return true
	case Worldwide:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleUser:
		return true
	default:
		return false
	}
}

// Defines values for SearchResultType.
const (
	SearchResultTypeGame      SearchResultType = "game"
	SearchResultTypeHardware  SearchResultType = "hardware"
	SearchResultTypePcListing SearchResultType = "pc_listing"
)

// Valid indicates whether the value is a known member of the SearchResultType enum.
func (e SearchResultType) Valid() bool {
	switch e {
	case SearchResultTypeGame:
		return true
	case SearchResultTypeHardware:
		return true
	case SearchResultTypePcListing:
		return true
	default:
		return false
	}
}

// Defines values for SubmissionStatus.
const (
	Approved  SubmissionStatus = "approved"
	Cancelled SubmissionStatus = "cancelled"
	Pending   SubmissionStatus = "pending"
	Rejected  SubmissionStatus = "rejected"
)

// Valid indicates whether the value is a known member of the SubmissionStatus enum.
func (e SubmissionStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Cancelled:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for VerdictRequestAction.
const (
	ApproveExisting VerdictRequestAction = "approve_existing"
	ApproveNew      VerdictRequestAction = "approve_new"
	Reject          VerdictRequestAction = "reject"
)

// Valid indicates whether the value is a known member of the VerdictRequestAction enum.
func (e VerdictRequestAction) Valid() bool {
	switch e {
	case ApproveExisting:
		return true
	case ApproveNew:
		return true
	case Reject:
		return true
	default:
		return false
	}
}

// Defines values for Visibility.
const (
	Listed   Visibility = "listed"
	Private  Visibility = "private"
	Unlisted Visibility = "unlisted"
)

// Valid indicates whether the value is a known member of the Visibility enum.
func (e Visibility) Valid() bool {
	switch e {
	case Listed:
		return true
	case Private:
		return true
	case Unlisted:
		return true
	default:
		return false
	}
}

// Defines values for EntriesSort.
const (
	EntriesSortBacklogRank EntriesSort = "backlog_rank"
	EntriesSortCreatedAt   EntriesSort = "created_at"
	EntriesSortName        EntriesSort = "name"
	EntriesSortPaid        EntriesSort = "paid"
	EntriesSortPurchasedAt EntriesSort = "purchased_at"
	EntriesSortRating      EntriesSort = "rating"
	EntriesSortReleaseDate EntriesSort = "release_date"
	EntriesSortValue       EntriesSort = "value"
)

// Valid indicates whether the value is a known member of the EntriesSort enum.
func (e EntriesSort) Valid() bool {
	switch e {
	case EntriesSortBacklogRank:
		return true
	case EntriesSortCreatedAt:
		return true
	case EntriesSortName:
		return true
	case EntriesSortPaid:
		return true
	case EntriesSortPurchasedAt:
		return true
	case EntriesSortRating:
		return true
	case EntriesSortReleaseDate:
		return true
	case EntriesSortValue:
		return true
	default:
		return false
	}
}

// Defines values for GroupBy.
const (
	GroupByItemType GroupBy = "item_type"
	GroupByLocation GroupBy = "location"
	GroupByPlatform GroupBy = "platform"
	GroupByStatus   GroupBy = "status"
	GroupByTag      GroupBy = "tag"
)

// Valid indicates whether the value is a known member of the GroupBy enum.
func (e GroupBy) Valid() bool {
	switch e {
	case GroupByItemType:
		return true
	case GroupByLocation:
		return true
	case GroupByPlatform:
		return true
	case GroupByStatus:
		return true
	case GroupByTag:
		return true
	default:
		return false
	}
}

// Defines values for Order.
const (
	Asc  Order = "asc"
	Desc Order = "desc"
)

// Valid indicates whether the value is a known member of the Order enum.
func (e Order) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for Tab.
const (
	Following Tab = "following"
	You       Tab = "you"
)

// Valid indicates whether the value is a known member of the Tab enum.
func (e Tab) Valid() bool {
	switch e {
	case Following:
		return true
	case You:
		return true
	default:
		return false
	}
}

// AcceptedStatus defines model for AcceptedStatus.
type AcceptedStatus string

// ActivityVerb defines model for ActivityVerb.
type ActivityVerb string

// AdminSubmission One queue row: the submission plus the live proposal from the entry join (display_name, item_type, platform_name, region, edition, first_release_date pre-fill the curation form; entries carry no variant - the single edition field is the idiom).
type AdminSubmission struct {
	// CoverUrl The entry's cover URL, live from the proposal join; prefills the curation cover field.
	CoverUrl  *string   `json:"cover_url,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// Developers The entry's developer credit facts, live from the proposal join; prefill the curation form.
	Developers       *[]string           `json:"developers,omitempty"`
	DisplayName      string              `json:"display_name"`
	Edition          *string             `json:"edition,omitempty"`
	EntryId          openapi_types.UUID  `json:"entry_id"`
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	Id               openapi_types.UUID  `json:"id"`
	ItemType         ItemType            `json:"item_type"`
	PlatformName     *string             `json:"platform_name,omitempty"`

	// Publishers The entry's publisher credit facts, live from the proposal join; prefill the curation form.
	Publishers *[]string          `json:"publishers,omitempty"`
	Region     string             `json:"region"`
	Status     SubmissionStatus   `json:"status"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// AdminSubmissionsPage defines model for AdminSubmissionsPage.
type AdminSubmissionsPage struct {
	Submissions []AdminSubmission `json:"submissions"`

	// TotalCount Full pending count, beyond this page.
	TotalCount int64 `json:"total_count"`
}

// BulkUpdateRequest Delta applied across the caller's own entries among entry_ids (foreign or unknown ids are silently not counted, same ownership-filtering posture as tag attachment). At least one of add_tag_ids / remove_tag_ids / status / storage_location must be present, else 400. storage_location's clearing rule is the OPPOSITE of the full-replacement update's: here an ABSENT storage_location leaves the field untouched, and an explicit empty string clears it.
type BulkUpdateRequest struct {
	AddTagIds    *[]openapi_types.UUID `json:"add_tag_ids,omitempty"`
	EntryIds     []openapi_types.UUID  `json:"entry_ids"`
	RemoveTagIds *[]openapi_types.UUID `json:"remove_tag_ids,omitempty"`
	Status       *EntryStatus          `json:"status,omitempty"`

	// StorageLocation Empty string clears the field; an absent field leaves it untouched (see the operation description).
	StorageLocation *string `json:"storage_location,omitempty"`
}

// BulkUpdateResult defines model for BulkUpdateResult.
type BulkUpdateResult struct {
	// UpdatedCount Count of the caller's own entries among entry_ids, whether or not any targeted field actually changed.
	UpdatedCount int `json:"updated_count"`
}

// CatalogPlatform One platform-catalog row with its known aliases.
type CatalogPlatform struct {
	// Aliases Alternate spellings and abbreviations (compare case-insensitively).
	Aliases []string `json:"aliases"`
	IgdbId  int64    `json:"igdb_id"`
	Name    string   `json:"name"`
}

// CatalogProvider defines model for CatalogProvider.
type CatalogProvider string

// CommunityMeta Facts curated at community mint time; retained after promotion as gap-fill (provider blocks win per-field where present).
type CommunityMeta struct {
	// CoverUrl User-supplied cover image URL (https, never fetched server-side; the client renders it with a broken-image fallback). Served as the product cover when no provider cover is present; retained after promotion as gap-fill.
	CoverUrl *string `json:"cover_url,omitempty"`

	// Developers Curated developer company names, one per element; served into entry credit snapshots when the provider block carries no developer credits (per-field gap-fill).
	Developers       *[]string           `json:"developers,omitempty"`
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	PlatformName     *string             `json:"platform_name,omitempty"`

	// Publishers Curated publisher company names; same gap-fill posture as developers.
	Publishers *[]string `json:"publishers,omitempty"`

	// Region Curated entry-vocabulary region fact (open-world; known values ntsc_u, ntsc_j, pal, region_free, korea, brazil, china).
	Region *string `json:"region,omitempty"`
}

// CommunityProductSpec The curated fields for approve_new; mirrors the enrichment mint request (single edition field, no variant).
type CommunityProductSpec struct {
	// CoverUrl Optional https cover image URL (validated by shape only, never fetched).
	CoverUrl *string `json:"cover_url,omitempty"`

	// Developers Curated developer company names, one per element.
	Developers *[]string `json:"developers,omitempty"`

	// Edition The entry idiom's single "Edition or variant" note.
	Edition          *string             `json:"edition,omitempty"`
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	Name             string              `json:"name"`
	PlatformName     *string             `json:"platform_name,omitempty"`

	// Publishers Curated publisher company names, one per element.
	Publishers *[]string `json:"publishers,omitempty"`

	// Region Curated entry-vocabulary region fact; stored under the community facts block (community.region), not the product's top-level region field.
	Region *string  `json:"region,omitempty"`
	Type   ItemType `json:"type"`
}

// CommunityProductsPage defines model for CommunityProductsPage.
type CommunityProductsPage struct {
	Products []Product `json:"products"`

	// TotalCount Full count of community products, beyond this page.
	TotalCount int64 `json:"total_count"`
}

// CompanyCredit defines model for CompanyCredit.
type CompanyCredit struct {
	Developer bool   `json:"developer"`
	Name      string `json:"name"`
	Publisher bool   `json:"publisher"`
}

// CurrencyCode defines model for CurrencyCode.
type CurrencyCode = string

// CurrencySpend defines model for CurrencySpend.
type CurrencySpend struct {
	Currency   string `json:"currency"`
	TotalCents int64  `json:"total_cents"`
}

// Dashboard defines model for Dashboard.
type Dashboard struct {
	ByItemType map[string]int   `json:"by_item_type"`
	ByPlatform []PlatformCount  `json:"by_platform"`
	ByStatus   map[string]int   `json:"by_status"`
	Pricing    DashboardPricing `json:"pricing"`

	// Spend Sum of price_paid_cents per currency, over entries that record a price.
	Spend        []CurrencySpend `json:"spend"`
	TotalEntries int             `json:"total_entries"`
}

// DashboardPricing defines model for DashboardPricing.
type DashboardPricing struct {
	// Available False when enrichment was unreachable; total_value_cents is then absent.
	Available bool `json:"available"`

	// ExcludedEntries Entries with pricing_mode disabled.
	ExcludedEntries int    `json:"excluded_entries"`
	PricedEntries   int    `json:"priced_entries"`
	TotalValueCents *int64 `json:"total_value_cents,omitempty"`

	// UnpricedEntries Entries whose effective product is unmatched or lacks a price for their packaging.
	UnpricedEntries int `json:"unpriced_entries"`
}

// DismissCandidateRequest defines model for DismissCandidateRequest.
type DismissCandidateRequest struct {
	Provider   CatalogProvider `json:"provider"`
	ProviderId int64           `json:"provider_id"`
}

// Entry One physical copy. On product-backed entries the catalog fields (item_type, display_name, platform, first_release_date, igdb_game_id) are immutable creation-time snapshots from the enrichment product and product_id remains the live join key for prices. A CUSTOM entry has no product_id: its display fields are user-owned and editable, platform carries the picked or normalized identity - name-only for escape-hatch free text - when supplied, and igdb_game_id is always absent. value_cents is composed at read time from the effective pricing product and the packaging-matched price field; (or, with pricing_mode custom, taken directly from custom_value_cents, packaging-independent); it is null when pricing_mode is disabled, the product is unmatched, no price exists for the packaging, or enrichment is temporarily unreachable.
type Entry struct {
	// BacklogRank Present exactly while status is backlog; server-generated.
	BacklogRank  *string        `json:"backlog_rank,omitempty"`
	BoxCondition *ItemCondition `json:"box_condition,omitempty"`

	// CoverUrl Cover art URL. For product-backed entries it is snapshotted from the product at creation (and refreshed on adoption). Custom entries may set their own (https, shape-validated). Absent on hardware and products without art (render a placeholder).
	CoverUrl  *string   `json:"cover_url,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	Currency  string    `json:"currency"`

	// CustomValueCents The user-set market value (USD cents). With pricing_mode custom it IS the entry's value; under any other mode it persists as "last custom price" memory.
	CustomValueCents *int64 `json:"custom_value_cents,omitempty"`

	// CustomValueEnteredCents The custom price exactly as the user typed it, in custom_value_entered_currency minor units (major units x 100, including zero-decimal currencies). Display metadata only: no aggregation reads it; custom_value_cents remains the USD value used everywhere.
	CustomValueEnteredCents *int64 `json:"custom_value_entered_cents,omitempty"`

	// CustomValueEnteredCurrency Currency of custom_value_entered_cents.
	CustomValueEnteredCurrency *string `json:"custom_value_entered_currency,omitempty"`

	// CustomValueSetAt Server-managed: stamped when custom_value_cents is first set or changes value, untouched otherwise. Read-only.
	CustomValueSetAt *time.Time `json:"custom_value_set_at,omitempty"`

	// Developers Developer company names snapshotted for the entry: IGDB credits where the product carries them, community curated lists as gap-fill, or the user's own facts on a custom entry. Absent when no credits are known.
	Developers  *[]string `json:"developers,omitempty"`
	DisplayName string    `json:"display_name"`

	// Edition Per-copy variant note ("first print (glitched rev)", "black edition"): the idiom for variants of cataloged items is an entry on the base product with the variant recorded here.
	Edition          *string             `json:"edition,omitempty"`
	ExternalRef      *string             `json:"external_ref,omitempty"`
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	HasBox           bool                `json:"has_box"`
	HasManual        bool                `json:"has_manual"`
	Id               openapi_types.UUID  `json:"id"`

	// IgdbGameId The recommendation identity: snapshotted from the entry's own product, or from the proxy target on custom game entries (owning a reproduction of X means playing X).
	IgdbGameId    *int64         `json:"igdb_game_id,omitempty"`
	ItemCondition *ItemCondition `json:"item_condition,omitempty"`
	ItemType      ItemType       `json:"item_type"`

	// LocalizedCoverUrl Region-picked box art URL (server-derived).
	LocalizedCoverUrl *string `json:"localized_cover_url,omitempty"`

	// LocalizedName Region-picked native-script title (server-derived from the entry's region; absent when the region has none).
	LocalizedName *string `json:"localized_name,omitempty"`

	// LocalizedNameTranslit Latin transliteration of localized_name's title (server-derived).
	LocalizedNameTranslit *string        `json:"localized_name_translit,omitempty"`
	ManualCondition       *ItemCondition `json:"manual_condition,omitempty"`
	MediaType             MediaType      `json:"media_type"`
	Notes                 *string        `json:"notes,omitempty"`
	Packaging             Packaging      `json:"packaging"`
	Pinned                bool           `json:"pinned"`

	// Platform The entry's platform: a creation-time snapshot of the product's platform (both fields) on product-backed entries, or a user-supplied platform on custom entries - both fields when picked from the catalog or normalized by the admin lever, name-only for escape-hatch free text. Absent when neither exists.
	Platform         *EntryPlatform      `json:"platform,omitempty"`
	PricePaidCents   *int64              `json:"price_paid_cents,omitempty"`
	PricingMode      PricingMode         `json:"pricing_mode"`
	PricingProductId *openapi_types.UUID `json:"pricing_product_id,omitempty"`

	// ProductId Absent on custom entries.
	ProductId *openapi_types.UUID `json:"product_id,omitempty"`

	// Publishers Publisher company names; same sourcing as developers.
	Publishers    *[]string           `json:"publishers,omitempty"`
	PurchasedAt   *openapi_types.Date `json:"purchased_at,omitempty"`
	PurchasedFrom *string             `json:"purchased_from,omitempty"`
	Rating        *int                `json:"rating,omitempty"`
	Region        string              `json:"region"`

	// RegionMismatchAckAt Null until the owner dismisses the region-mismatch banner; cleared whenever region or product changes.
	RegionMismatchAckAt *time.Time  `json:"region_mismatch_ack_at,omitempty"`
	Source              EntrySource `json:"source"`
	Status              EntryStatus `json:"status"`
	StorageLocation     *string     `json:"storage_location,omitempty"`
	Tags                []TagRef    `json:"tags"`
	UpdatedAt           time.Time   `json:"updated_at"`
	ValueCents          *int64      `json:"value_cents,omitempty"`
}

// EntrySource defines model for Entry.Source.
type EntrySource string

// EntryCreate Product-backed: product_id comes from a prior enrichment resolve and the catalog fields are snapshotted server-side (display_name/item_type/platform_name/first_release_date must NOT be sent). Custom (no product_id): display_name and item_type are required, platform_name and first_release_date optional; pricing_mode defaults to disabled and must not be auto. media_type accepts only physical (the column already allows digital: the API widens when platform sync arrives). source is server-set manual. pricing_product_id is required when pricing_mode is proxy; box_condition requires has_box and manual_condition requires has_manual. custom_value_cents is required when pricing_mode is custom.
type EntryCreate struct {
	BoxCondition *ItemCondition `json:"box_condition,omitempty"`

	// CoverUrl Custom entries only; an https cover image URL (validated by shape, never fetched).
	CoverUrl                   *string `json:"cover_url,omitempty"`
	Currency                   *string `json:"currency,omitempty"`
	CustomValueCents           *int64  `json:"custom_value_cents,omitempty"`
	CustomValueEnteredCents    *int64  `json:"custom_value_entered_cents,omitempty"`
	CustomValueEnteredCurrency *string `json:"custom_value_entered_currency,omitempty"`

	// Developers Custom entries only: developer company names, one per element. Ignored on product-backed creation, where the snapshot derives credits from the product.
	Developers *[]string `json:"developers,omitempty"`

	// DisplayName Custom entries only (required there).
	DisplayName *string `json:"display_name,omitempty"`

	// Edition Per-copy variant note; the idiom for variants of cataloged items.
	Edition *string `json:"edition,omitempty"`

	// FirstReleaseDate Custom entries only.
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	HasBox           *bool               `json:"has_box,omitempty"`
	HasManual        *bool               `json:"has_manual,omitempty"`
	ItemCondition    *ItemCondition      `json:"item_condition,omitempty"`

	// ItemType Custom entries only (required there).
	ItemType        *ItemType      `json:"item_type,omitempty"`
	ManualCondition *ItemCondition `json:"manual_condition,omitempty"`

	// MatchProvenance Whose choice the matched product is. Send user only when the add flow's manual match picked the price listing; automated repoints (region edits, the entry rematch) never touch user rows. Not accepted on update - the server stamps user when the narrow product_id re-match arm fires.
	MatchProvenance *EntryCreateMatchProvenance `json:"match_provenance,omitempty"`
	MediaType       *EntryCreateMediaType       `json:"media_type,omitempty"`
	Notes           *string                     `json:"notes,omitempty"`
	Packaging       Packaging                   `json:"packaging"`
	Pinned          *bool                       `json:"pinned,omitempty"`

	// PlatformIgdbId Custom entries only; the canonical platform id from the picker (surfaces the entry in the platform filter).
	PlatformIgdbId *int64 `json:"platform_igdb_id,omitempty"`

	// PlatformName Custom entries only.
	PlatformName     *string             `json:"platform_name,omitempty"`
	PricePaidCents   *int64              `json:"price_paid_cents,omitempty"`
	PricingMode      *PricingMode        `json:"pricing_mode,omitempty"`
	PricingProductId *openapi_types.UUID `json:"pricing_product_id,omitempty"`

	// ProductId Omit for a custom (off-catalog) entry.
	ProductId *openapi_types.UUID `json:"product_id,omitempty"`

	// Publishers Custom entries only; publisher company names, one per element.
	Publishers    *[]string           `json:"publishers,omitempty"`
	PurchasedAt   *openapi_types.Date `json:"purchased_at,omitempty"`
	PurchasedFrom *string             `json:"purchased_from,omitempty"`
	Rating        *int                `json:"rating,omitempty"`

	// Region Entry region. Known values ntsc_u, ntsc_j, pal, region_free, korea, brazil and china are first-class: labeled in the UI, filterable, normalize-lever promotion targets, with release-date chains, availability rows, and localized display snapshots per region (ntsc_u and region_free render the canonical presentation by design). korea, brazil and china have no PriceCharting axis, so they price from base listings as their deliberate proxy. Any other non-empty string is stored verbatim as a display fact and prices like ntsc_u until the value graduates to the known set.
	Region          string                `json:"region"`
	Status          *EntryStatus          `json:"status,omitempty"`
	StorageLocation *string               `json:"storage_location,omitempty"`
	TagIds          *[]openapi_types.UUID `json:"tag_ids,omitempty"`
}

// EntryCreateMatchProvenance Whose choice the matched product is. Send user only when the add flow's manual match picked the price listing; automated repoints (region edits, the entry rematch) never touch user rows. Not accepted on update - the server stamps user when the narrow product_id re-match arm fires.
type EntryCreateMatchProvenance string

// EntryCreateMediaType defines model for EntryCreate.MediaType.
type EntryCreateMediaType string

// EntryGroup defines model for EntryGroup.
type EntryGroup struct {
	Entries []Entry `json:"entries"`
	Key     string  `json:"key"`
	Label   string  `json:"label"`
}

// EntryList One page of the sorted, filtered sequence. Exactly one of entries/groups is present (groups when group_by was requested, partitioning this page only).
type EntryList struct {
	Entries *[]Entry      `json:"entries,omitempty"`
	Groups  *[]EntryGroup `json:"groups,omitempty"`

	// PricingAvailable False when enrichment was unreachable; every value_cents is null.
	PricingAvailable bool `json:"pricing_available"`

	// TotalCount Size of the full filtered set, before pagination.
	TotalCount int `json:"total_count"`
}

// EntryPlatform The entry's platform: a creation-time snapshot of the product's platform (both fields) on product-backed entries, or a user-supplied platform on custom entries - both fields when picked from the catalog or normalized by the admin lever, name-only for escape-hatch free text. Absent when neither exists.
type EntryPlatform struct {
	// IgdbPlatformId Absent on name-only custom entries.
	IgdbPlatformId *int64 `json:"igdb_platform_id,omitempty"`
	Name           string `json:"name"`
}

// EntryStatus defines model for EntryStatus.
type EntryStatus string

// EntryUpdate Full replacement of the mutable state; an absent optional field is cleared (the edit form holds the whole entry). media_type and custom-ness are immutable. product_id accepts one narrow change - re-matching an auto-priced entry off an unmatched game product onto a product of the same game and platform (see the field description); anything else answers 400 code invalid_product_change. That re-match stamps match_provenance=user; automated region repoints only ever run on match_provenance=auto entries. On custom entries display_name is required and platform_name/first_release_date replace like any optional field; on product-backed entries all three are rejected. tag_ids replaces the tag set; absent means no tags. custom_value_cents is required when pricing_mode is custom.
type EntryUpdate struct {
	BoxCondition *ItemCondition `json:"box_condition,omitempty"`

	// CoverUrl Custom entries only; an https cover image URL (validated by shape, never fetched).
	CoverUrl                   *string `json:"cover_url,omitempty"`
	Currency                   *string `json:"currency,omitempty"`
	CustomValueCents           *int64  `json:"custom_value_cents,omitempty"`
	CustomValueEnteredCents    *int64  `json:"custom_value_entered_cents,omitempty"`
	CustomValueEnteredCurrency *string `json:"custom_value_entered_currency,omitempty"`

	// Developers Custom entries only; developer company names, one per element (full replacement).
	Developers *[]string `json:"developers,omitempty"`

	// DisplayName Custom entries only (required there).
	DisplayName *string `json:"display_name,omitempty"`

	// Edition Per-copy variant note; the idiom for variants of cataloged items.
	Edition *string `json:"edition,omitempty"`

	// FirstReleaseDate Custom entries only.
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	HasBox           *bool               `json:"has_box,omitempty"`
	HasManual        *bool               `json:"has_manual,omitempty"`
	ItemCondition    *ItemCondition      `json:"item_condition,omitempty"`
	ManualCondition  *ItemCondition      `json:"manual_condition,omitempty"`
	Notes            *string             `json:"notes,omitempty"`
	Packaging        Packaging           `json:"packaging"`
	Pinned           bool                `json:"pinned"`

	// PlatformIgdbId Custom entries only; the canonical platform id from the picker.
	PlatformIgdbId *int64 `json:"platform_igdb_id,omitempty"`

	// PlatformName Custom entries only.
	PlatformName     *string             `json:"platform_name,omitempty"`
	PricePaidCents   *int64              `json:"price_paid_cents,omitempty"`
	PricingMode      PricingMode         `json:"pricing_mode"`
	PricingProductId *openapi_types.UUID `json:"pricing_product_id,omitempty"`

	// ProductId Narrow re-match. Accepted only when the entry is product-backed with pricing_mode auto, its current product is a game with no price mapping, and the new product is a game of the same family (same igdb game and platform); the same id as the entry already has is a no-op. Anything else answers 400 code invalid_product_change; enrichment unreachable answers 502 code enrichment_unavailable and leaves the entry unchanged. Snapshotted display fields stay as they are.
	ProductId *openapi_types.UUID `json:"product_id,omitempty"`

	// Publishers Custom entries only; publisher company names, one per element (full replacement).
	Publishers    *[]string           `json:"publishers,omitempty"`
	PurchasedAt   *openapi_types.Date `json:"purchased_at,omitempty"`
	PurchasedFrom *string             `json:"purchased_from,omitempty"`
	Rating        *int                `json:"rating,omitempty"`

	// Region Entry region. Known values ntsc_u, ntsc_j, pal, region_free, korea, brazil and china are first-class: labeled in the UI, filterable, normalize-lever promotion targets, with release-date chains, availability rows, and localized display snapshots per region (ntsc_u and region_free render the canonical presentation by design). korea, brazil and china have no PriceCharting axis, so they price from base listings as their deliberate proxy. Any other non-empty string is stored verbatim as a display fact and prices like ntsc_u until the value graduates to the known set. On an auto-provenance game entry, a region change repoints the entry to the sibling catalog product whose listing prices that region; snapshotted display fields re-derive from it.
	Region          string                `json:"region"`
	Status          EntryStatus           `json:"status"`
	StorageLocation *string               `json:"storage_location,omitempty"`
	TagIds          *[]openapi_types.UUID `json:"tag_ids,omitempty"`
}

// FXRates defines model for FXRates.
type FXRates struct {
	// Base Always USD.
	Base string `json:"base"`

	// Date Upstream snapshot date (YYYY-MM-DD), not the fetch time.
	Date string `json:"date"`

	// Rates Target-units-per-USD by ISO 4217 code. USD itself is omitted (it is the base; conversion short-circuits).
	Rates map[string]float64 `json:"rates"`
}

// Handle defines model for Handle.
type Handle = string

// Identities defines model for Identities.
type Identities struct {
	Identities []Identity `json:"identities"`
}

// Identity defines model for Identity.
type Identity struct {
	CreatedAt time.Time `json:"created_at"`

	// Email Informational; the email the provider asserted when this identity last signed in.
	Email    *string            `json:"email,omitempty"`
	Id       openapi_types.UUID `json:"id"`
	Provider string             `json:"provider"`
}

// IgdbMeta Projection of the raw IGDB payload held in igdb_raw; refreshed on its own cadence.
type IgdbMeta struct {
	Companies []CompanyCredit `json:"companies"`
	CoverUrl  *string         `json:"cover_url,omitempty"`
	FetchedAt time.Time       `json:"fetched_at"`

	// FirstReleaseDate Earliest date for the product's platform; the game-level first release when IGDB lists no dated rows for the platform.
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	Franchises       []string            `json:"franchises"`
	GameId           int64               `json:"game_id"`
	Genres           []string            `json:"genres"`

	// Localizations Per-region presentations; absent both on projections predating the feature and on games with no localizations at all (an empty slice is omitted rather than sent).
	Localizations *[]Localization `json:"localizations,omitempty"`
	Name          string          `json:"name"`

	// ReleaseDates Per-region release dates for the product's platform, the earliest concrete date per region. Region values are canonical IGDB names (europe, north_america, australia, new_zealand, japan, china, asia, worldwide, korea, brazil). JP twin platforms fold into their sibling (SNES/Super Famicom, NES/Famicom).
	ReleaseDates *[]ReleaseDate `json:"release_dates,omitempty"`
	SimilarGames []int64        `json:"similar_games"`
	Themes       []string       `json:"themes"`
}

// ItemCondition defines model for ItemCondition.
type ItemCondition string

// ItemType defines model for ItemType.
type ItemType string

// LandingPage defines model for LandingPage.
type LandingPage string

// LibraryEntry defines model for LibraryEntry.
type LibraryEntry struct {
	IgdbGameId int64 `json:"igdb_game_id"`
	Rating     *int  `json:"rating,omitempty"`

	// Status The caller's own status vocabulary; scoring only distinguishes "dropped".
	Status *string `json:"status,omitempty"`
}

// Localization One region's presentation of the game, merged from IGDB game_localizations and tagged alternative names. region is an IGDB region identifier served verbatim (ja-JP, EU, ko-KR, zh-CN, zh-TW, pt-BR; open-world - new identifiers pass through). name is the native-script title, translit its latin transliteration, cover_url the region's own box art; each is independently optional (rows are sparse - readers fall back per field).
type Localization struct {
	CoverUrl *string `json:"cover_url,omitempty"`
	Name     *string `json:"name,omitempty"`
	Region   string  `json:"region"`
	Translit *string `json:"translit,omitempty"`
}

// MappingRequest defines model for MappingRequest.
type MappingRequest struct {
	// PcProductId Null clears the mapping (the product becomes unmatched and held).
	PcProductId *int64 `json:"pc_product_id"`
}

// MediaType defines model for MediaType.
type MediaType string

// NormalizeResult defines model for NormalizeResult.
type NormalizeResult struct {
	Normalized int `json:"normalized"`
	Scanned    int `json:"scanned"`
	Skipped    int `json:"skipped"`
}

// Packaging defines model for Packaging.
type Packaging string

// PlatformCatalog defines model for PlatformCatalog.
type PlatformCatalog struct {
	Platforms []CatalogPlatform `json:"platforms"`
}

// PlatformCount defines model for PlatformCount.
type PlatformCount struct {
	Count int    `json:"count"`
	Name  string `json:"name"`
}

// PlatformRef defines model for PlatformRef.
type PlatformRef struct {
	IgdbPlatformId int64 `json:"igdb_platform_id"`

	// LogoUrl IGDB platform logo; the display fallback for products without cover art.
	LogoUrl *string `json:"logo_url,omitempty"`
	Name    string  `json:"name"`

	// ReleaseRegions Distinct canonical IGDB release regions for this game on this platform (japan, north_america, europe, ...), ordered by that region's earliest release date on the platform (dateless rows last, then alphabetical). Platform-exact: JP twin platforms are NOT folded here (a Famicom row stays on Famicom), unlike the product projection's date fold - the physical release is platform-specific. Populated on game search results only; absent on product payloads and hardware results.
	ReleaseRegions *[]ReleaseRegion `json:"release_regions,omitempty"`
}

// PricechartingMeta The PriceCharting mapping and current prices; refreshed daily. Absent from a product when no candidate cleared the match confidence threshold (no guessing) and the mapping has not been corrected by an admin.
type PricechartingMeta struct {
	AsOf            time.Time `json:"as_of"`
	CibCents        *int64    `json:"cib_cents,omitempty"`
	ConsoleName     string    `json:"console_name"`
	LooseCents      *int64    `json:"loose_cents,omitempty"`
	MatchConfidence float64   `json:"match_confidence"`
	NewCents        *int64    `json:"new_cents,omitempty"`
	PcName          string    `json:"pc_name"`
	PcProductId     int64     `json:"pc_product_id"`
	Verified        bool      `json:"verified"`
}

// PricingMode defines model for PricingMode.
type PricingMode string

// Problem defines model for Problem.
type Problem struct {
	// Code The full house code vocabulary across every service (Problem is shared, and the bff relays upstream codes verbatim).
	Code     *ProblemCode `json:"code,omitempty"`
	Detail   *string      `json:"detail,omitempty"`
	Instance *string      `json:"instance,omitempty"`
	Status   int          `json:"status"`
	Title    string       `json:"title"`
	Type     string       `json:"type"`
}

// ProblemCode The full house code vocabulary across every service (Problem is shared, and the bff relays upstream codes verbatim).
type ProblemCode string

// Product defines model for Product.
type Product struct {
	// Community Facts curated at community mint time; retained after promotion as gap-fill (provider blocks win per-field where present).
	Community *CommunityMeta     `json:"community,omitempty"`
	CreatedAt time.Time          `json:"created_at"`
	Edition   *string            `json:"edition,omitempty"`
	Id        openapi_types.UUID `json:"id"`

	// Igdb Projection of the raw IGDB payload held in igdb_raw; refreshed on its own cadence.
	Igdb *IgdbMeta `json:"igdb,omitempty"`

	// MatchHold Present true when an admin clear holds this product's mapping against a future automated match (resolve, or the entry-side re-match).
	MatchHold *bool  `json:"match_hold,omitempty"`
	Name      string `json:"name"`

	// Origin Emitted only for admin-minted community products (absent means provider-identified). Community products live outside the provider identity indexes; their curated name is their identity.
	Origin   *ProductOrigin `json:"origin,omitempty"`
	Platform *PlatformRef   `json:"platform,omitempty"`

	// Pricecharting The PriceCharting mapping and current prices; refreshed daily. Absent from a product when no candidate cleared the match confidence threshold (no guessing) and the mapping has not been corrected by an admin.
	Pricecharting *PricechartingMeta `json:"pricecharting,omitempty"`

	// Region Provider hardware identity fact; community products carry their region under community.region instead.
	Region    *string     `json:"region,omitempty"`
	Type      ProductType `json:"type"`
	UpdatedAt time.Time   `json:"updated_at"`
	Variant   *string     `json:"variant,omitempty"`
}

// ProductOrigin defines model for ProductOrigin.
type ProductOrigin string

// ProductType defines model for ProductType.
type ProductType string

// ProfileCard The cross-user projection of a user. Never email, never roles.
type ProfileCard struct {
	AvatarUrl         *string            `json:"avatar_url,omitempty"`
	Handle            Handle             `json:"handle"`
	ProfileVisibility Visibility         `json:"profile_visibility"`
	UserId            openapi_types.UUID `json:"user_id"`
}

// ProfileSocialSummary defines model for ProfileSocialSummary.
type ProfileSocialSummary struct {
	FollowerCount  int  `json:"follower_count"`
	FollowingCount int  `json:"following_count"`
	ViewerFollows  bool `json:"viewer_follows"`
}

// PromoteCandidate defines model for PromoteCandidate.
type PromoteCandidate struct {
	FoundAt    time.Time       `json:"found_at"`
	Name       string          `json:"name"`
	Provider   CatalogProvider `json:"provider"`
	ProviderId int64           `json:"provider_id"`
	Score      float64         `json:"score"`
}

// PromoteCandidateProduct defines model for PromoteCandidateProduct.
type PromoteCandidateProduct struct {
	Candidates []PromoteCandidate `json:"candidates"`
	Product    Product            `json:"product"`
}

// PromoteCandidatesPage defines model for PromoteCandidatesPage.
type PromoteCandidatesPage struct {
	Products []PromoteCandidateProduct `json:"products"`

	// TotalCount Full count of flagged community products.
	TotalCount int64 `json:"total_count"`
}

// PromoteRequest Provider identity for an in-place promotion. type game products require igdb_game_id + platform_igdb_id and accept an optional pc_product_id (the listing can also arrive later via the mapping fix, once provider); console and accessory products require pc_product_id. The identity the product re-enters the index with completes with the doc's stored region/edition/variant.
type PromoteRequest struct {
	IgdbGameId     *int64 `json:"igdb_game_id,omitempty"`
	PcProductId    *int64 `json:"pc_product_id,omitempty"`
	PlatformIgdbId *int64 `json:"platform_igdb_id,omitempty"`
}

// Providers defines model for Providers.
type Providers struct {
	// Providers Subset of: google, twitch, dev
	Providers []string `json:"providers"`
}

// Recommendation defines model for Recommendation.
type Recommendation struct {
	CoverUrl         *string             `json:"cover_url,omitempty"`
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	Genres           []string            `json:"genres"`
	IgdbGameId       int64               `json:"igdb_game_id"`
	Name             string              `json:"name"`
	Score            float64             `json:"score"`
}

// RefreshAccepted defines model for RefreshAccepted.
type RefreshAccepted struct {
	Status AcceptedStatus `json:"status"`
}

// ReleaseDate defines model for ReleaseDate.
type ReleaseDate struct {
	Date   openapi_types.Date `json:"date"`
	Region ReleaseRegion      `json:"region"`
}

// ReleaseRegion defines model for ReleaseRegion.
type ReleaseRegion string

// RematchAccepted defines model for RematchAccepted.
type RematchAccepted struct {
	Status AcceptedStatus `json:"status"`
}

// ReorderRequest Neighbor entry ids around the drop slot; null marks a list edge. Both null is invalid.
type ReorderRequest struct {
	AfterId  *openapi_types.UUID `json:"after_id,omitempty"`
	BeforeId *openapi_types.UUID `json:"before_id,omitempty"`
}

// ResnapshotResult defines model for ResnapshotResult.
type ResnapshotResult struct {
	EntriesUpdated int `json:"entries_updated"`
	ProductsFailed int `json:"products_failed"`
	ProductsSeen   int `json:"products_seen"`
}

// ResolveRequest type game requires igdb_game_id + platform_igdb_id (the platform must be one the game released on). Game identity is listing-keyed - (game, platform, PriceCharting listing) - so edition/variant on a game resolve are ignored (entry-level facts, like pc_listing); region is a matching input only (see the region property) and never joins identity. Without pc_product_id the resolve auto-matches by the game name (region-steered) through the shared listing-search cache and lands on the winning listing's product; below the confidence threshold, or with the provider down, it lands on the game+platform's single unmatched product instead - never guessed. Optional match_hint (game only, ignored elsewhere) reweights the scoring toward variant text without changing the search query; a hint nothing matches makes the resolve conservative (unmatched). With pc_product_id (a manual match: the exact listing the user chose) auto-match is skipped and the resolve finds or mints the product carrying that listing (match_confidence 1.0, verified false); unknown id answers 404 unknown_pc_product, provider failure 502 upstream_unavailable. Resolves never touch an existing product's mapping; corrections stay on the admin mapping endpoint. console/accessory require pc_product_id; region/edition/variant distinguish physical variants and are part of hardware identity. type pc_listing requires pc_product_id and mints a price-anchor product for that exact listing; region/edition/variant are ignored (the listing IS the exact variant).
type ResolveRequest struct {
	Edition        *string `json:"edition,omitempty"`
	IgdbGameId     *int64  `json:"igdb_game_id,omitempty"`
	MatchHint      *string `json:"match_hint,omitempty"`
	PcProductId    *int64  `json:"pc_product_id,omitempty"`
	PlatformIgdbId *int64  `json:"platform_igdb_id,omitempty"`

	// Region For console/accessory: part of hardware identity, distinguishing physical variants. For game: a matching input only - the entry region (ntsc_u, ntsc_j, pal, region_free, korea, brazil, china) steers which PriceCharting listing auto-match lands on (JP and PAL listings live under region-prefixed or JP-named console axes; korea, brazil and china have no provider axis and match like ntsc_u) and is never stored on the product; ignored when pc_product_id is present; unknown values behave like ntsc_u. Ignored for pc_listing.
	Region  *string     `json:"region,omitempty"`
	Type    ProductType `json:"type"`
	Variant *string     `json:"variant,omitempty"`
}

// Role defines model for Role.
type Role string

// SavedView defines model for SavedView.
type SavedView struct {
	CreatedAt time.Time              `json:"created_at"`
	Id        openapi_types.UUID     `json:"id"`
	Name      string                 `json:"name"`
	Params    map[string]interface{} `json:"params"`

	// PublishedAt Stamped on each transition into listed.
	PublishedAt *time.Time `json:"published_at,omitempty"`

	// Slug URL slug derived from the name (underscore transform); unique per user on its folded key.
	Slug       string     `json:"slug"`
	UpdatedAt  time.Time  `json:"updated_at"`
	Visibility Visibility `json:"visibility"`
}

// ScoreResponse defines model for ScoreResponse.
type ScoreResponse struct {
	// Degraded True when candidate metadata fetches failed and some candidates were skipped.
	Degraded        bool             `json:"degraded"`
	Recommendations []Recommendation `json:"recommendations"`
}

// SearchResult Flat result with a type discriminator. Game results carry the igdb_* fields; hardware results carry the pc_* fields plus the PriceCharting category (Systems, Controllers, Accessories). pc_listing results carry the pc_* fields, the PriceCharting category (empty when the provider lists none), and the standard per-listing loose/cib/new prices so variant prints are tellable apart.
type SearchResult struct {
	Category    *string `json:"category,omitempty"`
	CibCents    *int64  `json:"cib_cents,omitempty"`
	ConsoleName *string `json:"console_name,omitempty"`
	CoverUrl    *string `json:"cover_url,omitempty"`

	// Developers Community rows only - the curated developer names, for based-add prefill.
	Developers       *[]string           `json:"developers,omitempty"`
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	IgdbGameId       *int64              `json:"igdb_game_id,omitempty"`
	ItemType         *ItemType           `json:"item_type,omitempty"`

	// Localizations Per-region presentations of a game result (games only).
	Localizations *[]Localization `json:"localizations,omitempty"`
	LooseCents    *int64          `json:"loose_cents,omitempty"`

	// MatchedRegion Set when the query matched a region's localized name or transliteration rather than the canonical name: that bundle's region identifier. Clients may present the region's data and preselect a matching entry region. Absent on canonical-name matches, hardware, pc_listing, and community results.
	MatchedRegion *string `json:"matched_region,omitempty"`
	Name          string  `json:"name"`
	NewCents      *int64  `json:"new_cents,omitempty"`

	// Origin Marks an interleaved community result (admin-minted, anchor-less); absent on provider results. Community results carry product_id + item_type + platform_name for the pick, community.cover_url as cover_url, and community.region as region. They are scored against the query by name similarity and merged into results by descending score (a provider result precedes a community result of equal score), capped at 10, for game and hardware searches only (never pc_listing). The provider cache stores provider results only - community items attach fresh on every search.
	Origin       *ProductOrigin      `json:"origin,omitempty"`
	PcProductId  *int64              `json:"pc_product_id,omitempty"`
	PlatformName *string             `json:"platform_name,omitempty"`
	Platforms    *[]PlatformRef      `json:"platforms,omitempty"`
	ProductId    *openapi_types.UUID `json:"product_id,omitempty"`

	// Publishers Community rows only - the curated publisher names, for based-add prefill.
	Publishers *[]string `json:"publishers,omitempty"`

	// Region Community rows only - the community facts region, entry vocabulary.
	Region *string          `json:"region,omitempty"`
	Type   SearchResultType `json:"type"`
}

// SearchResultType defines model for SearchResultType.
type SearchResultType string

// SearchResults defines model for SearchResults.
type SearchResults struct {
	// Degraded True when the provider was unreachable and the local catalog answered instead.
	Degraded bool           `json:"degraded"`
	Results  []SearchResult `json:"results"`
}

// SharedEntry The cross-user entry projection - a strict whitelist. No money fields (price paid, values, currency, purchase provenance, pricing mode) and no personal fields (status, rating, notes, location, backlog rank, external refs) may ever be added here without a deliberate privacy decision.
type SharedEntry struct {
	BoxCondition     *ItemCondition      `json:"box_condition,omitempty"`
	CoverUrl         *string             `json:"cover_url,omitempty"`
	CreatedAt        time.Time           `json:"created_at"`
	Developers       *[]string           `json:"developers,omitempty"`
	DisplayName      string              `json:"display_name"`
	Edition          *string             `json:"edition,omitempty"`
	FirstReleaseDate *openapi_types.Date `json:"first_release_date,omitempty"`
	HasBox           bool                `json:"has_box"`
	HasManual        bool                `json:"has_manual"`
	Id               openapi_types.UUID  `json:"id"`
	IgdbGameId       *int64              `json:"igdb_game_id,omitempty"`
	ItemCondition    *ItemCondition      `json:"item_condition,omitempty"`
	ItemType         ItemType            `json:"item_type"`

	// LocalizedCoverUrl Region-picked box art URL (server-derived).
	LocalizedCoverUrl *string `json:"localized_cover_url,omitempty"`

	// LocalizedName Region-picked native-script title (server-derived from the entry's region; absent when the region has none).
	LocalizedName *string `json:"localized_name,omitempty"`

	// LocalizedNameTranslit Latin transliteration of localized_name's title (server-derived).
	LocalizedNameTranslit *string        `json:"localized_name_translit,omitempty"`
	ManualCondition       *ItemCondition `json:"manual_condition,omitempty"`
	MediaType             MediaType      `json:"media_type"`
	Packaging             Packaging      `json:"packaging"`
	Pinned                bool           `json:"pinned"`

	// Platform The entry's platform: a creation-time snapshot of the product's platform (both fields) on product-backed entries, or a user-supplied platform on custom entries - both fields when picked from the catalog or normalized by the admin lever, name-only for escape-hatch free text. Absent when neither exists.
	Platform   *EntryPlatform      `json:"platform,omitempty"`
	ProductId  *openapi_types.UUID `json:"product_id,omitempty"`
	Publishers *[]string           `json:"publishers,omitempty"`
	Region     string              `json:"region"`
	Tags       []TagRef            `json:"tags"`
}

// SharedEntryGroup defines model for SharedEntryGroup.
type SharedEntryGroup struct {
	Entries []SharedEntry `json:"entries"`
	Key     string        `json:"key"`
	Label   string        `json:"label"`
}

// SharedEntryList Exactly one of entries/groups is present (groups when the stored params group).
type SharedEntryList struct {
	Entries    *[]SharedEntry      `json:"entries,omitempty"`
	Groups     *[]SharedEntryGroup `json:"groups,omitempty"`
	TotalCount int                 `json:"total_count"`
}

// ShelfSocialSummary defines model for ShelfSocialSummary.
type ShelfSocialSummary struct {
	// CommentCount Live comments only.
	CommentCount int                `json:"comment_count"`
	LikeCount    int                `json:"like_count"`
	ShelfId      openapi_types.UUID `json:"shelf_id"`
	ViewerLikes  bool               `json:"viewer_likes"`
}

// Submission One catalog-submission lifecycle row for an entry. Rows persist as history (rejected and cancelled included; the rolling creation cap counts every attempt); deleting the entry removes them with it. product_id is the verdict's resolved product - recorded before adoption so an approve_new retry never mints twice.
type Submission struct {
	CreatedAt    time.Time           `json:"created_at"`
	EntryId      openapi_types.UUID  `json:"entry_id"`
	Id           openapi_types.UUID  `json:"id"`
	ProductId    *openapi_types.UUID `json:"product_id,omitempty"`
	RejectReason *string             `json:"reject_reason,omitempty"`

	// ResolutionAckAt When the submitter acknowledged an approved verdict (closed the approval banner). Absent until acknowledged.
	ResolutionAckAt *time.Time       `json:"resolution_ack_at,omitempty"`
	ReviewedAt      *time.Time       `json:"reviewed_at,omitempty"`
	Status          SubmissionStatus `json:"status"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

// SubmissionStatus defines model for SubmissionStatus.
type SubmissionStatus string

// Tag defines model for Tag.
type Tag struct {
	EntryCount int                `json:"entry_count"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
}

// TagCreate defines model for TagCreate.
type TagCreate struct {
	Name string `json:"name"`
}

// TagRef A tag as embedded on an entry (no usage count).
type TagRef struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// UnmatchedProductsPage defines model for UnmatchedProductsPage.
type UnmatchedProductsPage struct {
	Products []Product `json:"products"`

	// TotalCount Full count of unmatched products, beyond this page.
	TotalCount int64 `json:"total_count"`
}

// ValueHistory defines model for ValueHistory.
type ValueHistory struct {
	// Available False when enrichment was unreachable; points is then empty.
	Available bool         `json:"available"`
	Points    []ValuePoint `json:"points"`
}

// ValuePoint defines model for ValuePoint.
type ValuePoint struct {
	Date       openapi_types.Date `json:"date"`
	ValueCents int64              `json:"value_cents"`
}

// VerdictRequest One admin verdict. approve_new requires product; approve_existing requires product_id; reject requires reason.
type VerdictRequest struct {
	Action VerdictRequestAction `json:"action"`

	// Product The curated fields for approve_new; mirrors the enrichment mint request (single edition field, no variant).
	Product   *CommunityProductSpec `json:"product,omitempty"`
	ProductId *openapi_types.UUID   `json:"product_id,omitempty"`
	Reason    *string               `json:"reason,omitempty"`
}

// VerdictRequestAction defines model for VerdictRequest.Action.
type VerdictRequestAction string

// ViewCreate defines model for ViewCreate.
type ViewCreate struct {
	Name string `json:"name"`

	// Params Opaque frontend view state; at most 8192 marshaled bytes.
	Params     map[string]interface{} `json:"params"`
	Visibility *Visibility            `json:"visibility,omitempty"`
}

// Visibility defines model for Visibility.
type Visibility string

// CatalogQ defines model for catalogQ.
type CatalogQ = string

// Cursor defines model for cursor.
type Cursor = string

// EntriesDeveloper defines model for entriesDeveloper.
type EntriesDeveloper = []string

// EntriesItemCondition defines model for entriesItemCondition.
type EntriesItemCondition = []ItemCondition

// EntriesItemType defines model for entriesItemType.
type EntriesItemType = []ItemType

// EntriesPackaging defines model for entriesPackaging.
type EntriesPackaging = []Packaging

// EntriesPublisher defines model for entriesPublisher.
type EntriesPublisher = []string

// EntriesRegion defines model for entriesRegion.
type EntriesRegion = []string

// EntriesSort defines model for entriesSort.
type EntriesSort string

// EntriesTagId defines model for entriesTagId.
type EntriesTagId = []openapi_types.UUID

// GroupBy defines model for groupBy.
type GroupBy string

// Offset defines model for offset.
type Offset = int

// Order defines model for order.
type Order string

// PlatformId defines model for platformId.
type PlatformId = []int64

// StatusFilter defines model for statusFilter.
type StatusFilter = []EntryStatus

// Tab defines model for tab.
type Tab string

// UserSearchQ defines model for userSearchQ.
type UserSearchQ = string

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L17k9s2lij+VVD6bZXVv6FkO5PdO9tdt7YcO9n1rGP7uu2ZnZ3kaiHySEKaBBQA7LYy5e9+C+cAIEhB",
	"EtVtZ+4j+SduisTj4OC8H3+blKrZKgnSmsnl3yZbrnkDFjT+VXLLa7X+H+7fQk4uJz+3oHeTYiJ5A+7P",
	"STHR8HMrNFSTS6tbKCam3EDD3ReNkK9Aru1mcvm0mNjd1n1irBZyPfn0qZiUrTZKHxrb/5oOuD8ESKsF",
	"mBdwC7XaAg5WgSm12Fqh3KjxJ+bGNVeMS+a+2rGG23IDht1tQDIud0ytmLCGGcm3ZqOshYpV4WvDhGG1",
	"MBaq+aTILji+21uzsNAgLBv+MULjqyd78CjcCy/p5X/sfuZa8126VffKcyUrQfvLw85NuijjW9n1/IOG",
	"1eRy8v897hDgMb1mHvcnOWtt7/G3I8vCj++1Ihx69GLe8vKGrx1sD6xmG184ezXd2OOX0y5rYTY5FI0/",
	"BRQ1vAGmbkHXfEtoKuSacdOh4yEc3MZZviQOvoO1R77+Rv5dqjs5u+V1C2zZljdgzRVT1u3MWKWhYjST",
	"YUrWO2ZaveIlsFauRG1BH75amiY8tafff3XvLV0rbQ8hinG/pXNXsOJtbR2R0sAtVAvuXgDZNpPLv9Jn",
	"jjDWwA0sKm7dn9tWlxtuwsu9LxFk7h0uKvclt4SWS17e1Gq90FzeTH4sDhPA93z9sto/kG/pV1ZyrXcO",
	"h569euWpGLN8bQ7B2/L1AleSgfdK6Ya7vbctvnIuwNdatdtvdoeAjT8vlrve5AGy25pbN7/70XLbGrf+",
	"hKjUquSe4lm+zkNMrVYGDp61/zV72k8Kx9JE49bS7UxIC2vQNLau4CBDox/zeOSOLcEgjn/hw+weAhxy",
	"Z/7yX198w8ILTFSGTQOnsxtgiHdCyZkVDURed3GQoPiBTqODkPafvp7sg+UkQtBJfock4OAVDKd9JqF2",
	"F2B3TR+fXonly0MLcD8dk3XCya1UXas7ur071eaPrzWgr4HrcnNfyaqjef/0dXFC0PoUvkRoPStL2Fqo",
	"PFCSpRvLtYUqs+Ri8qy04lbY3Z9AL/e3C9XCbcldQHED1cJsoF45GqeaBqRNngT+FJ5k56oaIa/bZSOM",
	"ybKZNxLYzy20wLS6u0SsNvF1tq1bwvRa3ALbarVVhtdspVWDj0n4+0kJyaaVMNua7xYO6AWLlKSI98f/",
	"QvynYEASUcFWQhu7SCk822qYrURd0y1rNd4y5ga5YpDSYSYVu+VacGnZjFYv5LqGMDpbCagrJ2+630Ql",
	"VHMx/8HRNLcZ0FYACedOQli0ut6H0Puwz0eG4Wvsw7tXBUEkAiKCxsHiyq3fLd/0109f44rmOWKfsLGU",
	"GDiIIIXJfdMJ1cdXHt9zRKsSlq14ac24beyfwtzzCpPRJIa0oJikmJH9ADoJfP83twFHMcewy31U2oNk",
	"7rORo3fc8QwBu4f92R1GOfPEEcb3/g5HqKOUuveqicTvGEg6GtRxkHZbnY3vjjaOw4ZPKdH/6wRficjU",
	"DZRIPz087QtDUWjuiZrJBjriq5Y/QWkzxNe85WvEgD7p6citGc2Kh2Q9c2JWWV4vStVKu49W37V1zbYg",
	"KyfH4jsFW8JOyYrZjTBsy9fgEOSkQDIAcrqX/hJy8PmmrW8+IAjfwc8tGJuzONSWM77d1gIqxkutjCeq",
	"vK5BPzJM3cnIEnij5JqFQzZsulIaxFoypVkrb5xGhUIc145P1CBt7TiIJRBAVXht8U6CNhuxnZEu5YC0",
	"Vca2GpziaPmacWt5uXEM+WLOnlnmCI5lSgJTK8arakFSv2GPmYZG3ULygPAN/6E0X8MiSNqsaY1lS2R/",
	"BtyZQG2Aff3kyXzvXceMauC4Nt3WEFjcm7dv31y/fP+tW4f7e9XW9UzDtuYluOUywtlH5pJtwO1Hsmff",
	"XH/7+v3+amrgt17QJS7aSqvacuPgxGWFxp+P21qUwjJotnbnNVJamGHC5jhtApzPpwp1N/veg371hFQS",
	"/+fTHA1MD/JzLn4cCR3I38PzymismUOJp4nGO750eOaP15+3sN1Bs6kBwG/cERJaJHOgppPIzwjD42S4",
	"O6dTFMGgNjekloHkHiBsz93jgPtjaETB7jaAVhWlkRRwuWOW6zU4vZ4Aw0vb8rresXLD5RpS4e0QIewv",
	"M7fV52QOfhu08KxkHoSHmTceOyGd3Qm7QeMqETReC24AzQ+Dm0Y/7I/8zBE16eRss4W6RiMSXujlUsOt",
	"wGM2bOpQ0FHKkhuYCWlAGmHFLdS7i/OEB7GulkOefVjDPSAnDdm5H7MIFqKw22Ow1upWeKNCULrcOAg5",
	"UUK54RqNRTlN6rlqmlYKu/seLM9wVCeLkYTlGJVjKf591ghpmZNnrpgGy4V0L6wsaCerNQovFTdszbek",
	"80y3fp1sWavyxrA7IdkW9Iyw8Q7ptmcR5yozHwzomWk9PyWFRDR8DU6pYdONtVtTMAmoqIBFGmBA37qv",
	"RAVXdK9q4aiGBlmhMd8SSnK21OoG5IwGXPG6XvLy5mLOrt0IFfJOklCrtrR+dvQYSMXipv2iTNjiOKgR",
	"HM5Sj577w0pUI4fxckem4wLZuXsMNbLOK4JExYS0yqu+XhIPph/vAPG7TA4RtVVHfqTaU8UMm3anG/bj",
	"D3b8Jbun6vMw9SSAMFFNUhB663vE7ESI6g7m3I3qAwbzsBY8mNmtKvmyrbneeYMDaktsqrYgZ3dKOwZI",
	"9BPtxYZJa8pFW9D/fyrYltfBVrFYaYCC3SgNvGBLzX8RdcHKjZDcH9Nxu/mnHEkK5OEt3YbrLZR59S/Q",
	"FMQP43Q3Jw9rJ4pIuLtijdBaec4OUgsSS4nqaJKr2TRnFSkS48m5dOQN/oPXDCnGPiG55bVADsiWO2Y2",
	"fAvophiQlqH88I9PvyomW24de5pcTv4nDn75+PGXvtk9dnaGX+dpThDtbBkHVHkyQz0ywVT1w+RbfyxK",
	"h/P4YeKEERjA5+lXf/h8Ro9w4Yfy21EDaIZgpOt7koPXAwjIFz2phxCSq+CEax0PJK4YGT7aZTzdn8bH",
	"c/r8okAxM2GEjwyzajurHbLGOdBIOIK2hAdjDVIDMcqbN/AsfxxBpg7YMPxOxhsw/HD3M1yUQcjvQB4W",
	"8HnMGHE7p20YzwldnyMn3wdMlQZT+I+XStXA5RFZN7kzue8Gq/UCcBoy0X2eXXOrNchy91xVdJYdxf3r",
	"s9l//vi333/6hxzFCN9db0FW+3st/c95Lk5wDKEx555IHLs/Um53L7jZLBXXmRUud4ueDZdXRHh5/bb3",
	"3r5SsjfLcrfYJqrbOKT3H6CSmkP95W7RmQIesDinzfhgjWPriZB669//VExMONv+vbtuG3fhUE1abLmo",
	"6ACQNIezKTDMIiradsOdAFIqXTFOX/ao97GV9THtIJHwU+WgMqRzvfdTSBd9rOifbIBHB9KjGPe2g/tA",
	"Fb/loubLGnKKY22A1IZEervjhrVSAy837rMrRhtAWdWDngx+wYaT2CQS+gIfy7qtoEohlY9qQA3Ob3LR",
	"qApYJYybOmvt8ApzdewEwiElax5pAWjl/ugHVr1RBhisVlBa76FE1VI46JGnvnJSVc2dHu2xEEVouwGh",
	"WQxbGmHS6c5wb/eZJWdgn0UdYRphzHMuKzEwhO9x2Gi7OHpzBqYOPCr691gTzD4zpKH6I+V2gxbKA5as",
	"zc6Ikjvmvd3N2RsZzmq25OWNl7ZEiKvw1i6v8kwTZ3Lfyxwuas6JXDC0Ea15AwtRXaDRXzRNa90ZHgjd",
	"MKlrO17GgFVcVuHfC1ExDQ0XMvGPox/8BnaIYIgPZs6esecfrt+/+d7L/htuvLXDD3OJpjy/rbBjt9bW",
	"gJ6pO7R7yApVN7fybtPRpoCypEAoohFTN7wWv0DFRAXSOvFohuL0DCPF3OLAlHwLs427Icxpt8zCR8tm",
	"RIeCfYjM/CkU3cXi9R3fmUB22IAkIUoaMoFp4BUavhKoJlcVaU0PuLiRcCVn4f76S0tG66nSRYZYla2x",
	"qimY5TcgWSU0lNbt1c1Lv6V0qEhmEbICR+NB2osrJpB2SCdlIih6kwgTiWLRs2Sl5Kag43VLho/CWBPI",
	"TTdn4Y4pwS9HyaHZKs21qHcp3c9p5b04tv34RzKaMfjIEQJ3G1FDcDkJw/zXV8GqtwYJqO5kIxKW6mMS",
	"+npuoOsR+8FzFBW4tuzDu1dz9h1emCw9oBNJ44hTVzehjo3XmU0dHmlYaTBI+yXjlfLOCvYcMSEO3fAd",
	"M2A9L1B3MhpA0WIxi0aMizl7Rp4SJdmG6+qOo+sskgPin6q1uKUpWUYdv6l5CRtVV6AvDlgo7xP0kUra",
	"Y4X3/VuQN1Eg2XFQabi+AUv3m00/XL9g+NXFnP35wPVzZ/XyugsMemTo6yuvJWNcOPpa6DpZJz4avCPc",
	"sB8mNTc2DIU36IcJa6BRekewGyE69HYJEgNhj+02nS3eGW+ndpBgboqKCVswIVl+dH8YrBES/cxo0W34",
	"T/GPj+zpkyduACcQOJr3C2g1q6AUjWOI9L0AB9oXng80YHnFLUer2aUjKXy91rAmJHeE1d2Mqwxt67El",
	"d2p0gK2jyXALeof+gwcCNMG/PdsJAcNp5wfPAn1V98FbA9ZflIF6QsSs4ZKvobp09K5x54Y0PAMjYUhg",
	"wOuvtHfseXQtEv8nouudMDBn74BXyEEHsLt3eNaLvHWyT+s878D7dMkwHjV4DcgR1POodAJBUyTWkWBC",
	"rsNdCxZ55EQB172jlKxXjnCG24GTRxIYHDZhGY4UoiX9ywWFDVgc6JmTImPgn1QW2PQHMoS6uywtm65r",
	"QeKDhtuLHyYF+2GydGpAsIH/MLm47IICEdB+PIPISyIo3n1oEGNisosiD8+Smw70KJK4p2FRpPlCxbrr",
	"tr/Fj+iIrRfIVf/22Uy7G24WS/Uxb3NyPzZctrzO/z42GC4RC/O01UGgaUBWRLSCMHqZZ+aBYzgU9EBF",
	"7Ey5/cfgmndH4JHTLSFy9Km6k5jewTT4QdCuvmL/wRrg0jiOjMH7/3ExmgQOEoDOlYLuFTVYq5Jk+MUR",
	"IYpSR2Ze9F+qj0GgYlMv3VWgxa33s+ydYDdHuIPHhpfcie0zeoFZYWsYTrN/mGTNvgpxJtE56q3cpAxJ",
	"GLO+hdVcmlpkqP8rboVk4fcQp6JWrD/CI5Nfdn52uiIPOPcGKsFHHfz37s1w8o6Y5SnoNk3CGp1RtRVS",
	"QpW/6qkF82TkUYxUCdafxA440rCTyoynPQT47vfu1eTTTnEeRaX6rw/CYKJIX/b0gp7H4ODAR5xab496",
	"w41qdTnMQTPnMc9e/tMoN3/8wN3R7Bw+UYr8apSY8zTN0nmaO9EjccHed94Ig5rxgpc3WdnttVO2W2kF",
	"BSlj8KXTsxthjDdu0FCzMBRbcilBX1FMmxfz0K/s6UqnTQbJ7hyZDQ8I0iAhzy6LibHAGye8GjccbEWZ",
	"jRX6bPF8+4jA1+OdbO/5+h2scvhzn8jrc+24ufjr1M6e0Me90OsYbp3mlQappifCFKlrqEdfksBuTwPj",
	"0Xo4nhfNjcf1HD/ImV1S48VlaiYslRPqkTWiAbpv+9FgVH0L0fw1MH1ipHIiLiWxWP2Mm8cRtI97HvrH",
	"mewaDDN+/eY9WwKjILJgGZn2TJMXlz1zK1kDwzS4tHDAgyQffDMzsfJRI1cDTwOl7hlmVTSw4RC4UKkw",
	"Jpq3Vs1ZhzSMY/KVT3+N5uUpueLrtpGM105R3jFe1+rOsEqsheU1Sf3P3r5kd04k9SFb0ahqdrJkTo+6",
	"RYWcMAZNUB70aBpxuDdn+0zJvRiAkrcgohh7xXqWtfCJYR7HafcDCaT/VlhDXrs9vgb6Jmtc/GIGv77p",
	"zR0aRiCPjh/6jKFDffNFSBv9cP3ivmaJw0QxYaXhv+OJr6dMWF9uhnvYFI/HYO0d+OX4gCz2ci0xvkbt",
	"OYqCqbdIDCCBRDIS6U00TgxtxZ8zfmhowTi5fzaN19K6pY8Jnz/XDnI13qYxava8BeLkVudDaeuEmSJe",
	"wxWvDRQnzRan3/+cWjuv6zeryeVfx+rvPxb3QobPonWirI3hoZLLEvo0zjHRyXBxf0YnerlRoqTb1Dne",
	"gntrzq5BVmQRx8VHTZ5XFVvV6u6R8fyKvg7+SLp6buBaGKdfXCEjb5C0a9gq4XBz6uV2vLNFklmsAUe7",
	"8LQfrbK0Cq3uzJy9VtbLAUQqSIQLmcDIsMkWbOiruGzJtVZ3fW8uORwZ142TXUgPjEUECHCYmZ2T+PvK",
	"fgfwIJckQ8VHuXGi9t+PqszHVT7QHnD6DnUFC7oMjhFsneRYqSRKZEn5hIQcO/TQbOrLlpjkzIWPnw+f",
	"UQ7exXycsW4vPHUUqTodwzrG4HGc6w6NH+OISs8MgnSld5e/jGXkTSMsBZoH08hUrVYhCenCOwQeaibJ",
	"4s7fIxD4M1hTTvLRB1pX9sOfQjjynP37A9IYUNHATAbU55Dbz8qaG3PJar6EGtNdyJf4svB3kcJQYpwJ",
	"Ri6naTlkozc+TsPLDjOkzOWGC2kK5oOpRC3sDmk5xZpEg20MiOkic7adfWdKu2Tk64978xlJQ/pDERFk",
	"FF7uWAVGrOXF/CAgNvwWmFTMXT147nPCGP8oTMGMcqPvQkyKI2foBvLczXjfsdCsglosMbSCVL45exbd",
	"31LJWS9j1qmXFE9+C3rJrWjcQLwLC+Ix/Eg4almLG/BHnZjOyNO71rxquQVUp91jSnMxYOcjosmT+NNR",
	"9KlnxOrRJx9pcsi0dfLGfPY824FBKmNjOmj2+Vet2u1+UF4Snzi+gk7OHncD+ahpvIKnkyHd5+HlWMbq",
	"8G5eiVyqPUbpOQXcZ88apTElPtQTYwZ+bkGWMGff+kAJn+/uJ3yM5aZMkrrHpv4Ryl2hGhUGt/rMJDQd",
	"uRvmFuFuQozbR36QTUv6bFCnxZ03DmFCziTv2fDDQ30xSmMYVyfbus7H+B7Nl7gWv0BaCiA9Taz5sFIa",
	"j11IvJnzMfGgw42ezpLoO5COVznxb1064SMbpBn206XPRFlxulR2422nFxnbgUcddCxzH+oUkmHjIHsO",
	"ITZjybjepEb6TRRog922H4C53HklqRGSIZssRkViDoItQCDboHjC3JVA+TwtL3bE2dXNf8Tt9dD07IMJ",
	"RSm/SDwsgVmgAL/zBfuAW5BU+mpbg0ULfqXVdku2/A3UtwdKbOEsVEjgQA5RWhLD41MIDXYsENLyCMFs",
	"3RWTCo4ntDZTLR6HORvl8MM9u9uo2uP0Rd9q7cQMhPtMgjH9qOR5qpB29u2orpIzi82isoqCiUSVekYB",
	"6CFEZbVyP3RB8BgmERR6Ja1CZ4T/0xN8ytX15vvuToUSELT7tPyDA9LO4iqwUgmX5g60YV8/ecJKtDVL",
	"NORG3YQ2MGfvKTfEa9xeQx+aLv67u599e8GazODebIBITH6/VjrU3hvBfRvxm73Zu9g990ZqNk8hcNCP",
	"4nGIpDEMbuwhytVhAsQ4lmRy153cKO56QDVnoUqMH5qQyfK1I9cxjIIiWaSispO/eQB+8wD8n+IBuBrt",
	"AWDT1YBMX/xmu//Ndj/SBv5AI/qvaYX99a2u/9dZUv++YWSvSTYL0sycPescEqmnxFu3zVAk2E9mclJL",
	"gWlhRJJtmmjESUTDr2KmUcO3W0wsCmEkEu4yH6WC3oo3wpE1/MNh2r7od3HVvS5i+R7aR4it2HCKjWZS",
	"zdQWjVznC4RXqT6c6MLx+3988hV93723aGXUQMl22JWroyW2MtTrYtdpG4J+qp2xPGR87JwwNogU+9UN",
	"21+Y8f1m6/7N1v3/hK3baXudahw0wi5dYFdglgDC2OvVUbHsaIgf1ohljUUUvZUnZn2g69wDJCzYFz6g",
	"yHdzmPJo8BHoBFtxpn3+gaGl/zva309GcOYsSt/9xztuY5J8L1HWQK74IaYvf7h+kQ37z0vJH7bGauBN",
	"EmjkkH36l7/85S+z77+fvXiRlPVB/RTznrMz6LDaQwU+OpKsWm9epTFk2yyJWA7Mp0iDZphsONuCnn24",
	"fuFu/8vrN+zrr57+N2Sdc0wGFNZAvXJ3UDUCkXJKCbYhoemKlUregsby72ajtJ2VQpetsKafwRoOYHCq",
	"CPQicBPaa+7U/o3Lqh7Wj/p9v/xUX5//K5/98mz2n09m//zj9F8uu78WP/7tSfHVHz4lv1/8S1ZZfUkZ",
	"SCKHLKL327g2Oj6had8bsBf6HMfOgSKOs19R5x65wdBwkbG+vJT0uY+/RQrn3uzXKuTGgLbBaIS+mFhD",
	"ALNzHTtBNjl/QB31tJbFiKLdSQGKBCBZSK6rZb4851ut3Es+LwhzCvgdpVNu+a5WvGIbtO1Kqneg+d1V",
	"P43cieOOt5S8QidYplqeE+vOQaB+7aiMT6lnTdtX78kOdhZ2jDEJfMt1LcB4GherF+x5WwiLHEP1tcso",
	"/9IPTiiEEKa0U6kY2fOcCNQN6wfLJGhk16+5LDfCDKB8MmEmSVQcofquQepzZ/DiHBXPzRt8vLSRCmkm",
	"GnXRw0QGY4+p6EatUJb2fIVT9UyJCLnGZOGgB/amZ9yihXnKZajMXQuKYg9kX3OUzuyGS5YUkh2Ft6+S",
	"uXKgOJjSm+LdcRgFJMI3j+CgDxYMGFsqWWqw9F0iRc8ZJTMGzYHKGgepGZGUcq+n0LpLjRK/3Sx4A1qU",
	"vGC8NVbzWvDCqdaLX4DXXFYF+4lvufS1QAvGjXsBq4veiWqof1zM2R/fMovVfP3y3dZqX1CWROkgaU6v",
	"X397/fi6dXv4jjeiVE3B3CP/xznn9Y6A+cLdqcxxGdGImmtM5jXn9iPaK8y1gea8qzMg+eGmxsLO/jLG",
	"oXtEYLj6IiHDPQqZZRfD9n8x30tI6xYAXC/8v29B7xZrpdzC/P/IQRcqQimVjwxN+/iF8de0s1JJo/Br",
	"N5QxSu+yQ7zi2KghlF4Mo5SqrolS4FbRKQoft7XSkB9GLDXXu1ikKeNCPo9M3kvP7xSYTDWOtGC7r1nT",
	"1d+8YqZUqEKiYa0irasVZgOG/RA8wz9M5qd7gaR7zWFGj8JlI2WIrjwyfZXbyxZrLE7VgF6HEAEkMTjj",
	"gFBLbB7n3uO+KrtTCJEYzYN6SrUHcIjwBIWylQAdalJHXXr6E5/98W3Bvv3gyM/s398V7JfN7Plr/N/7",
	"Pxdsa2ffvLtiXSFkNkNzYTemYVuObTa0atebizkL7lGKnN7LAy9i7jVKSXUuHbtgUZhJUjr9UfvU9SsG",
	"vNy4iZKiTHXiVp2i6IA5cVuuDXnCORYhXzl+t+TlDVJ91LBP1zQ+WBP3QDJrnpoleenH0c4PkkO478mA",
	"e7j8W7k4aoPGsqhdhwdvD6b4hGCsWAKlInZBAQ77NgipnEtAtrUPZKKWaafignpLzG4y5rmnbQi7CHmf",
	"oJclXq+DBe5QY4gu6iZfjNCUfOBySX+8ERhVcrqQZBimSCfsBshtu9c8NTaIA17jl6VYYrNFZfJUOxYN",
	"JdNTBjWCLDFe7xi0njjFkrsZstvrVTXd12HD4weFEhWTw8FlYQHvqIjK6cioEaytVmuVD2Pot4R075Ee",
	"1Jkvqe2BLwI4KA9Whrpn82MluQ8KzkRBcrWEkBliCaCeVBvkaP+hl6SF8f4gr+N3sT5enh1Iv0Eons/n",
	"FwXD3pshuC2aOh+ZTgxPpfdQLaebwz2twRhSBGtubOErmdbbDV+Cdcu/mLNwrjOsy3WZEZ4dJ3j95j0K",
	"0b7SDpvyIC9jsxRj+Q6rGQW5uWCtRJNySho7peuRCWovMkZ8KeQWh20lEJuZLZRiJco5e6u2bc19IhKC",
	"12BbSqaRYsWIlxiIFycnAwQJA7G6nP/qfDHfNxQ+aZQaXowjVcDfpt1R8gYWJ771nQiBB1HEW/BjihJM",
	"almpuKi72lIxSz6Y132pqVAeNQbexTQ1p/KtBJpkMKDKbNzBTaVi6xaMEXJ9EZ2iYUVUdsYxRJCsVFpj",
	"8JXDZy4pVjPbuMos1OqMGn1ieVZtFK8MHK6HhSzirCEpHK4D0EjjslNwz6rqUh5pHlIecrUfHu8WtBND",
	"qxGlz/vDd0sZgDMDimSawh/tIcwP4QMJ9/bpgOjsmoRwKipjgdUL8pxcq2UNTY5FjoljwI+f+ziGCqw3",
	"8+4bYaWxIfPziPsoo8o7Wf6Iwn6KUftSHjRMnCoP1W4zWUqCLvCNag2Q2z9pwuB7AFKQvFN+RAls6kdE",
	"5+KG61C7Fr0aq5Wj3I4NtMGN4wY1UWfyikLUq/l2AR9LgIoENGq8u5DKLlaqlfRMrmpROjq3CK2o0Zy+",
	"aGWCV/lohdiH0o0YUad7FCZZKb0UVYUh0Bt0lyxKpepK3SVPsOCt4xDeTL/wgRmLWsgbXET8JR07Pozf",
	"SypFh/+kGI2lqnbJn6UXbJJH4aOFVWEUH97BNdbJyYd7JD94RpA8wejr5O8wtJMTFmHZ2B1Z3iwyMMfn",
	"Ky5IusZulHIdR0lh4P4t5KILPXcPEHiTYqK0WAu5SM8gbMJrT8kTPMhQbXHwPMyWPuuX1MbHGlagHWXy",
	"766EI17976n2NmitNNbIQdC5LWy1WmswJnmqoTU4lk+hHrxmoF4tqOG0D6Vf9WbrGnkeeuy7h/Yfam5h",
	"UYtGULB++gvVuamo9s5icMfcI8pu8H+kk1qlFg2XuzDlot9ltJW8deKjExtpWt/qc7ESH22rIXniDW/h",
	"z459pA/7IWK9XzJPwkEG2hLPJz7oX33sO5tuDx94QtZ97B72P7wVcNcBCf/qhjnAb3C5GX4TUPW0gyrp",
	"eXfPYsXHmjufUWvypDc2+P6i4OMkwcMFsq1uvY8qCH0kXMYkji5SD2sbeGF2zR1/ZZytWnLGxOwEEken",
	"HtFjZVXqIoQFm0KIYN+RPqYdDFGjc7LGceFv6LP9ehTfei9QTENCAMwaR9CrTFsdNu2lHgS0n0WbYXUx",
	"Z8/3P8Oy+Kq1uP2epzm6lYWs4KPTCcj/EUrVJiZH0b3tAHdG3cLUMvBp2ORxROBoX+c5EqQW2i106lvc",
	"H3WLyoCU+tfT/rxZl8pkDztGMYdxwKsDRWTHVJj0+BBqTN6v/BsGo4/02ad9pc4rs9ZH3Z67I1CtI8Tu",
	"DE8Lags+dOvQkI4LP/ethDLuCieJzrCwyLYXX0CphXP2GoMFUUgJySta1dlerbfc8sN26U2Mljl2yj6m",
	"5lMnQNwKIyjw8NS3f+refEiX9a6rul9ydi0Hzt29dq1Kwevrtml4zktFIgvoxRGzIr3jWPiRlxz/BO1F",
	"IDNC1RzMvD/N3pgHdtkoC7HfS26HrTzvZh5Wvn+9njHFxJRKj7MwjOsvE4kHDVx0gBkD18OyT3jjrF51",
	"/TPLZn/H+Ua1vcs3nHOUqlvfmH1+xn58Wfg9rD/fqibX5j73+8Jd+fx2EnfaAX7dsWknBDlWO6Oczhjh",
	"PccWEL382Zhc2e+N8zs2zNyhrtoYJuAGj37MntmKnHQhhrh00mhtlC9ByWpuQbNbwXsWzJX4WDAly06g",
	"usDATcfk4qTI5vbX3Jt8zt5vEmEltYlrmGFmIHkUUUyjaKOQjm26oveVKh/FsG6SWh57uf+xFxwOpq2f",
	"F3NwH4NiLqFqDPLl0AqBbQ735zK53nlLbDOxumRrpdboL78TttwUrILbM+o+HyCceUrxrld9P6cEHo0t",
	"vF/jgfsEzt0DCQ5yvHszod4i9kOPaNw8mNHeEnK+9uE8LmA/fB9i9ode58O21DS4a7/96NiD6xSbMzxM",
	"hwL6cZIja30XJwtiOjkYyaneOR6duB7i7ibkl/CBd5Nigp5KxzA3QuKbBl+KwXeTYoLRd5NiQuF3WRn/",
	"HVnH/p7Hh/bjg5zqNYj1Zql0bB1tGNdOEiK6q9WWmVrZK+pZ1nCNfQ4dN2FQrWHOvlF2Qz9iXA0aVTP6",
	"x8oelPgPxIEkXcKwisz9vv6UhUlIszgU7OFT6xZel8yL+IHzBWvw8ZcMgBwR/9F/f3+SYm9t+VNHI9HB",
	"U+9Ejljz+ZSoMe052bFy9hIwuTBEpAX/dcWwGdq/UlpnMMOYIILMbmAHFZux6XrQY7Hv3/WvX7AZM4oN",
	"uD31D/Kz+grnKC9RVd8pWcV82DjHxs3olO9U8ourNPyNxXInQm5b61PyQ2WSGFiNOLIjjy/p2z8pIbsk",
	"Bupdplo7EMFoEL/O1irfe9CEAj64ETRJ+VKlM2MBNFQXIUqO0sTQ9RQB6f3/JS83PkWVy8qEgIg7IWUC",
	"x0fR3HjFllCrO99UfN+7jabFKHpFi1ql7mTBhO3P4lb+u3CEXc/5LgYsZgmTkQmDAR3g0H0O1ZzFVv/e",
	"qkrdlSh8pN4V8UyhNoAVmS+YhjtHtnwmXYjatOqO6ypWPMCOkzEuZsPlOgS6e7j93ILeXTHOcEqpKK84",
	"nEzDb2J3CDo4J/+CvqUIymncYWxY1xe6ea9eLRWFx0CTKIrHHnDlRhm4SBAD3YwU8RXdjGEVK4HQ16yJ",
	"qYRpe64djcy7aaZD3zR7On9SsODSYlgl4eKKeZ8DZmLHtOqv2b4vo+hwwhGlVgPmT+f8EXPmKZHpVdjl",
	"kmpNJf05Oxv4VQiZwIAiTJ9WMilzFXQUkBWmU86DYvK4U0qyusjVAc0hjfTtgnFicQxUd7CImUalc88E",
	"6zW4jrR0RLWPE1h0H0/NdwqecVlukmYiFD3FbR9RDq67R/FSJS80ScRR/Nv5Uned76SX9/2HEQ25RgeI",
	"uOs1aoZfTfc6bGj/Tul9dLo8fPZFijyIzkP8oeajDm6XB9jMrFeQOk3KHp167jNELhiyDcPuNqLc5Plp",
	"SmYiJZ/+8S1i59tnr7r0a3SukMvAM6WthpX4SG2A//h25hhW1ZkF0MtyKhG8SwX8KIxvQ4FL6bKwib2K",
	"QDK81h/C/AIPC4hP5afKQY8MHzXfUTWfmLMEXEgyW9cKAAMq4yUekyx9D9dI4uY4cR9y0S9ZWU/VPZcE",
	"1hAvJkgsszrJNb+F6k8C7j5PQuhIH+thKzLXvDmSsNwT67tth3oXVb5hp2/QqSTF/GMQPXU5wWQod8jU",
	"k3hkz6a6XWfStt+9Yu4XttegjmQ5vDyo29MCfNGTVoqfW0of8xXvMa/BR5newC4bvHsvp9q9/DM5h1sw",
	"ljs49MaNB3ieG+7aQeUdmK0TqjKGBVhrXkHOMRb96l3UZuxmSwlZhpGyhHTEqAa6Vw27Aw1BuMoXPO33",
	"lRxv4x5YxE6Z1+IW92fMAgyF1k5hHfCtGgOl3Y8kunMSSirh3mqE5FZpr5OFeOHoICbd7//3dSOu9mKE",
	"kze3ZXyPbeuW5M8+nym5hbUTwqbXO+PgVrDnSlqt6hq0KbB8kWOr1JC4JzUdma04OhMlocZSSJHJhMxg",
	"CRddwJ6xXFZOU9iCnoXJMfr1cSmWj6m0EVbaMCpqE9j1lSLCLdS+KpATC7JJQH5hWXr32QN3j1taj1bQ",
	"i34TDJVPpJEQJtGV0/PVhByTXDolf8Yrp9zBSlDh4PEG2Xvafu8hfz6kNeq5idbkl193F4yUWOPrTH+u",
	"3Od7RmlDtTgk8l5D0jgVdeLYoIV3uRddNSFkbU5RGfRDTTO++1WDJAq/qNgsW1nVEDu3JkmBc/a8Flhc",
	"tOG7WOC7l8qHJJ4q94CBGkqbStTQK+SUNN8M60B5Nej3RaRyRUKDiEh07sReksR4kebcCPfPHX71PZlp",
	"UdYBjYXL9nfFpmlQltu500VnNRhzMUgjIWIagJEEYvVJdiKC/y5p5Pe7QfO+mG0vypuki/i8S+Dkpsvm",
	"HBxJiFniJh71e19ZDQ1BDmt9DF2Hz0sqhsZ8LrdbOWoelECLAmHYCRW1KikSlEZkUz4EgsPAEipwmvwe",
	"XNWKwc8tr+nri4KVnCw5lj19QhQ0lsKLrJZsUrEYKKk+ibWSHKlxGWTzQ9XI7J1QIOTdyqjHOLeWUxVw",
	"g6UgQoy7mzlEvj1EBT8s4p+dQjiIrDsQDjG6vOKxYnoneWBXWe/z8cBDxPjIauIv1ECfRig82esSGOb3",
	"jeFLBUzihfn8i4NZXHsD7MfJBXQ/HRyXDmbupx/0JMFBF4QoDCJfi3XXyPCJNIFCIg8oCHFVo5C5J7qf",
	"pRbQPFlgoysg1lo4GjxIKJKEEM4Yx2p5mAInLLiDmLPXijVKQqwfN6XCfFsuqsLbTwoWijgXLBRuZF31",
	"uyLUGWWNqsC7SZSTs01XttywKfkrC0YFHrCymRs7lI8rmM+ZYJrLm4LBR0oDYRpW5gLlAySPS2wPFxIz",
	"g6mf98sFilteOppeCuO4xZetSL4vm9/DoNKX2MfTlGHN6bMi5e8plCdlmk+VZc6UYR4fnX8fwf8zNWc8",
	"U2+AanGkSP07b0il7h6+LgUVpPf9f70p6SJLx7s58kWT+8NnSmkMp+ksVqE/SigsyZMGIYkPlHJbJYxZ",
	"3yItXdFf6KtcDQ8nOfVHeGTyy87P/vDmlr0ui8c+7UpNfNES3aPqcKZ1Fh4kGN1HfPkyHeR/rd7usXH7",
	"fr/2E0z3M3XsStn437NvV7KOfPeu+7XkskFJqRhZialJ18X8wU23TgDuzNZbewd7Oi75RBzPqQji6w3U",
	"qxPJCCEz+EAs9CtxS2oBhGY183ytEXEDx1IVKDtzJMXwOQhuzDFZDXHs3jKKwdYGw2bhFXMy8/WyvAQ/",
	"63I3WS1WUO7KGrBQhw/Aptai7J3TrpyIJYxl3LCNcGiKXTioVQ5ZHZxQW1Pd7rJuK6ioFotWNZVr9v3D",
	"nIZPUekhcZxbC83WXlw5YRRiuEfsOqx8KfmGrPXC9loz+VJYt6ArgaERIbs1RgrMmIZSaSf8+h5rvKLw",
	"b2YUZhxuUSxfSLhjGtysZFLwUSN3ooSs5fo+CZiYWT5WmLtPQ4STr9OpLTRwc4AtIQRbB6AFL2+yPsM/",
	"R4rlcMha0IyXN1Ld1VBhAbUI1SocDZuWtTK+Xgj9yGu25FKCvohGSKoqno6VqUZ6ELwa8HKcdybjwkq7",
	"S9XV8j7fzZhj1hEnkhrbZ7kHhytLK3rFzPBwHJOAAVRQIdzarGHhPV/n2fbuGI18mJP7iEM1nTkHiPd8",
	"/RzhlqlI5idLe1T1C1w/Le7bRs8LZvvVzbFZGDcMmiWg7q1kJKtYFqc1fA1EDDNs/gvBMbeFDyFAz1vL",
	"P2Mq02dIXdoLkDQFW8JOoVnKtyj9wklMf+J1C/9GjG8fLg/vM+qbHRAz84WC8wY1enP0CeDC37pvTmoO",
	"aYEDP8tBUNCI989xONWp7cTJ+WHTUbJLJc5zMLTbCUMUKOl51HwgC4TQxBBIFX6NEZnDV3zopFtA9xux",
	"2mwdq3JY7jaZvyPacb5IvLPkemTiY7Sb+9t5vYXyXnJEECAGnblOEVK/6eyBCbg7g4Q/fXKKho8NmRrg",
	"xZb/3GIrEGlBVswJFbEVqWWNMpb94ek/f8Uars2G11iwzFIu+d6e+nFF45yWaYRRr5E32mgtHCrM6Deb",
	"B226jCgf+PGKSSspzgu1D2OzEoETlqBstbC76zIWl14C16Cfte4Ewl/fBez545/fY86We9sRMvy1A9PG",
	"2u3k0ycslbVSWR8PwYbVVDE5xPX7ZAAjPsbCU6WSVqO/R/haipXQUDqSPWf/hpVEvBcPoUxOdmQfFLDa",
	"YOzZhktU3P2ojwy7E7obvOhCeWgvLECEhoU5e60ww/TZ25du1NCrwPH7LbcbEzp57a06lh1iwrr9aagp",
	"ft5hCrl2/8tyc8PWIP/LRwcYCtkbDhZTErBoV0AvJmQtZPDi8q14TINUj73TnoqOTW7XNwDbAGm3j24M",
	"KtZGuuXkyfzp/Ak65bcg+VZMLie/nz+Z/546d24cdnz69L8CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
